// ========================================
// Static combat data constants (no DOM dependencies)
// ========================================

// ========================================
// BUILDING DATA (Outpost, Keep, Town Center)
// ========================================

function cloneValue(value) {
  if (Array.isArray(value)) return value.map((entry) => cloneValue(entry));
  if (value && typeof value === "object") {
    const next = {};
    Object.entries(value).forEach(([key, entry]) => {
      next[key] = cloneValue(entry);
    });
    return next;
  }
  return value;
}

export const BUILDING_ENHANCEMENT_DEFS = {
  courtArchitects: {
    id: "courtArchitects",
    name: "Court Architects",
    kind: "tech",
    icon: "assets/images/technologies/court-architects-3.png",
    description: "+30% HP.",
    defaultActive: false,
    effects: { hpPct: 30 },
  },
  arrowUpgrades: {
    id: "arrowUpgrades",
    name: "Arrow Upgrades",
    kind: "tech",
    icon: "assets/images/technologies/steeled-arrow-2.png",
    description: "+1 ranged attack per tier for this building's arrows.",
    mode: "level",
    defaultLevel: 0,
    labels: ["Arrows: 0", "Steeled: +1", "Balanced: +2", "Platecutter: +3"],
    icons: [
      "assets/images/technologies/steeled-arrow-2.png",
      "assets/images/technologies/steeled-arrow-2.png",
      "assets/images/technologies/balanced-projectiles-3.png",
      "assets/images/technologies/platecutter-point-4.png",
    ],
    effectsByLevel: [
      {},
      { baseArrowDmgAdd: 1, garrisonArrowDmgAdd: 1 },
      { baseArrowDmgAdd: 2, garrisonArrowDmgAdd: 2 },
      { baseArrowDmgAdd: 3, garrisonArrowDmgAdd: 3 },
    ],
  },
  fortificationsMacedonian: {
    id: "fortificationsMacedonian",
    name: "Fortifications",
    kind: "tech",
    civs: ["Macedonian Dynasty"],
    icon: "assets/images/technologies/fortifications-tier1-2.png",
    description: "+10% HP per research tier, up to +60%.",
    mode: "level",
    defaultLevel: 0,
    labels: [
      "Fortifications: 0",
      "Fortifications: +10%",
      "Fortifications: +20%",
      "Fortifications: +30%",
      "Fortifications: +40%",
      "Fortifications: +50%",
      "Fortifications: +60%",
    ],
    icons: [
      "assets/images/technologies/fortifications-tier1-2.png",
      "assets/images/technologies/fortifications-tier1-2.png",
      "assets/images/technologies/fortifications-tier2-2.png",
      "assets/images/technologies/fortifications-tier3-3.png",
      "assets/images/technologies/fortifications-tier4-3.png",
      "assets/images/technologies/fortifications-tier5-4.png",
      "assets/images/technologies/fortifications-tier6-4.png",
    ],
    effectsByLevel: [
      {},
      { hpPct: 10 },
      { hpPct: 20 },
      { hpPct: 30 },
      { hpPct: 40 },
      { hpPct: 50 },
      { hpPct: 60 },
    ],
  },
  sharpeningStonesMacedonian: {
    id: "sharpeningStonesMacedonian",
    name: "Sharpening Stones",
    kind: "tech",
    civs: ["Macedonian Dynasty"],
    icon: "assets/images/technologies/sharpening-stones-tier1-2.png",
    description: "+1 ranged attack per research tier, up to +6.",
    mode: "level",
    defaultLevel: 0,
    labels: [
      "Sharpening: 0",
      "Sharpening: +1",
      "Sharpening: +2",
      "Sharpening: +3",
      "Sharpening: +4",
      "Sharpening: +5",
      "Sharpening: +6",
    ],
    icons: [
      "assets/images/technologies/sharpening-stones-tier1-2.png",
      "assets/images/technologies/sharpening-stones-tier1-2.png",
      "assets/images/technologies/sharpening-stones-tier2-2.png",
      "assets/images/technologies/sharpening-stones-tier3-3.png",
      "assets/images/technologies/sharpening-stones-tier4-3.png",
      "assets/images/technologies/sharpening-stones-tier5-4.png",
      "assets/images/technologies/sharpening-stones-tier6-4.png",
    ],
    effectsByLevel: [
      {},
      { baseArrowDmgAdd: 1, garrisonArrowDmgAdd: 1 },
      { baseArrowDmgAdd: 2, garrisonArrowDmgAdd: 2 },
      { baseArrowDmgAdd: 3, garrisonArrowDmgAdd: 3 },
      { baseArrowDmgAdd: 4, garrisonArrowDmgAdd: 4 },
      { baseArrowDmgAdd: 5, garrisonArrowDmgAdd: 5 },
      { baseArrowDmgAdd: 6, garrisonArrowDmgAdd: 6 },
    ],
  },
  textiles: {
    id: "textiles",
    name: "Textiles",
    kind: "tech",
    icon: "assets/images/technologies/textiles-2.png",
    description:
      "Villager durability upgrade shown for reference only in building duels.",
    defaultActive: false,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  bancoRepairs: {
    id: "bancoRepairs",
    name: "Banco Repairs",
    kind: "ability",
    civs: ["Malians"],
    icon: "assets/images/technologies/banco-repairs-2.png",
    description:
      "Repair-cost modifier shown for reference only in building duels.",
    defaultActive: false,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  daimyoTownCenter: {
    id: "daimyoTownCenter",
    name: "Daimyo Line",
    kind: "tech",
    civs: ["Japanese"],
    icon: "assets/images/technologies/daimyo-manor-1.png",
    description:
      "Town Center upgrade chain: Daimyo Manor, Daimyo Palace, Shogunate Castle.",
    mode: "level",
    defaultLevel: 0,
    labels: ["Daimyo: Off", "Manor", "Palace", "Shogunate"],
    icons: [
      "assets/images/technologies/daimyo-manor-1.png",
      "assets/images/technologies/daimyo-manor-1.png",
      "assets/images/technologies/daimyo-palace-2.png",
      "assets/images/technologies/shogunate-castle-3.png",
    ],
    effectsByLevel: [
      {},
      { hpAdd: 1000, baseArrowsAdd: 1 },
      { hpAdd: 2000, baseArrowsAdd: 1, fireArmorAdd: 2 },
      {
        hpAdd: 3000,
        fireArmorAdd: 3,
        lockedEmplacementsAdd: ["Rocket Emplacement"],
      },
    ],
  },
  englishCapitalArrows: {
    id: "englishCapitalArrows",
    name: "Capital Arrowslits",
    kind: "ability",
    civs: ["English", "House of Lancaster"],
    icon: "assets/images/abilities/ability-network-of-castles-1.png",
    description: "Capital Town Centers fire one extra base arrowslit arrow.",
    defaultActive: false,
    effects: { baseArrowsAdd: 1 },
  },
  templarCapitalHp: {
    id: "templarCapitalHp",
    name: "Templar Headquarters",
    kind: "ability",
    civs: ["Knights Templar"],
    icon: "assets/images/buildings/town-center.png",
    description: "Capital Town Center variant with +1000 HP.",
    defaultActive: false,
    effects: { hpAdd: 1000 },
  },
  chineseCapitalHandcannon: {
    id: "chineseCapitalHandcannon",
    name: "Capital Handcannon Slits",
    kind: "ability",
    civs: ["Chinese", "Zhu Xi's Legacy"],
    icon: "assets/images/technologies/handcannon-slits-2.png",
    description:
      "Capital Town Center swaps arrowslits for Handcannon Slits. Shown for reference only.",
    defaultActive: false,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  fortifyOutpost: {
    id: "fortifyOutpost",
    name: "Fortify Outpost",
    kind: "tech",
    icon: "assets/images/technologies/fortify-outpost-2.png",
    description: "+1000 HP, +5 fire armor.",
    defaultActive: false,
    effects: { hpAdd: 1000, fireArmorAdd: 5 },
  },
  reinforcedDefenses: {
    id: "reinforcedDefenses",
    name: "Reinforced Defenses",
    kind: "tech",
    civs: ["Holy Roman Empire", "Order of the Dragon"],
    icon: "assets/images/technologies/reinforced-defenses-4.png",
    description: "+25% HP.",
    defaultActive: false,
    effects: { hpPct: 25 },
  },
  slateAndStoneConstruction: {
    id: "slateAndStoneConstruction",
    name: "Slate and Stone Construction",
    kind: "tech",
    civs: ["Holy Roman Empire", "Order of the Dragon"],
    icon: "assets/images/technologies/slate-and-stone-construction-3.png",
    description: "+5 fire armor.",
    defaultActive: false,
    effects: { fireArmorAdd: 5 },
  },
  earthenCoreWalls: {
    id: "earthenCoreWalls",
    name: "Earthen Core Walls",
    kind: "tech",
    civs: ["Golden Horde"],
    icon: "assets/images/technologies/earthen-core-walls-3.png",
    description: "+300 HP, +3 fire armor.",
    defaultActive: false,
    effects: { hpAdd: 300, fireArmorAdd: 3 },
  },
  paxMongolica: {
    id: "paxMongolica",
    name: "Pax Mongolica",
    kind: "tech",
    civs: ["Mongols"],
    icon: "assets/images/technologies/pax-mongolica-4.png",
    description: "+225 HP, +3 fire armor.",
    defaultActive: false,
    effects: { hpAdd: 225, fireArmorAdd: 3 },
  },
  castleTurret: {
    id: "castleTurret",
    name: "Castle Turret",
    kind: "tech",
    civs: ["Rus"],
    icon: "assets/images/technologies/castle-turret-1.png",
    description: "+2 damage to all Wooden Fortress projectiles.",
    defaultActive: false,
    effects: { baseArrowDmgAdd: 2, garrisonArrowDmgAdd: 2 },
  },
  castleWatch: {
    id: "castleWatch",
    name: "Castle Watch",
    kind: "tech",
    civs: ["Rus"],
    icon: "assets/images/technologies/castle-watch-1.png",
    description:
      "+6 line of sight. Shown for reference only in building duels.",
    defaultActive: false,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  boilingOil: {
    id: "boilingOil",
    name: "Boiling Oil",
    kind: "tech",
    icon: "assets/images/technologies/boiling-oil-3.png",
    description: "Adds a close-range boiling oil attack.",
    defaultActive: false,
    effects: { lockedEmplacementsAdd: ["Boiling Oil"] },
  },
  houseOfWisdomInfluence: {
    id: "houseOfWisdomInfluence",
    name: "House of Wisdom Influence",
    kind: "source",
    group: "source",
    civs: ["Abbasid Dynasty", "Ayyubids"],
    source: "House of Wisdom",
    icon: "assets/images/abilities/ability-house-of-wisdom-influence-1.png",
    description: "+5 fire armor while affected by House of Wisdom influence.",
    defaultActive: false,
    effects: { fireArmorAdd: 5 },
  },
  divineDefense: {
    id: "divineDefense",
    name: "Divine Defense",
    kind: "source",
    group: "source",
    civs: ["Zhu Xi's Legacy"],
    icon: "assets/images/abilities/ability-divine-defense-1.png",
    description: "+1 range while Divine Defense is active.",
    defaultActive: false,
    effects: { rangeAdd: 1 },
  },
  praesidiumInfluence: {
    id: "praesidiumInfluence",
    name: "Praesidium Influence",
    kind: "source",
    group: "source",
    civs: ["Byzantines"],
    icon: "assets/images/abilities/ability-praesidium-4.png",
    description: "-5% incoming damage per active Cistern water level.",
    mode: "level",
    defaultLevel: 0,
    labels: [
      "Praesidium: Off",
      "Water 1: -5%",
      "Water 2: -10%",
      "Water 3: -15%",
      "Water 4: -20%",
      "Water 5: -25%",
    ],
    icons: [
      "assets/images/abilities/ability-praesidium-1.png",
      "assets/images/abilities/ability-praesidium-1.png",
      "assets/images/abilities/ability-praesidium-1.png",
      "assets/images/abilities/ability-praesidium-4.png",
      "assets/images/abilities/ability-praesidium-4.png",
      "assets/images/abilities/ability-praesidium-4.png",
    ],
    effectsByLevel: [
      {},
      { damageResistancePct: 5 },
      { damageResistancePct: 10 },
      { damageResistancePct: 15 },
      { damageResistancePct: 20 },
      { damageResistancePct: 25 },
    ],
  },
  emergencyRepairs: {
    id: "emergencyRepairs",
    name: "Emergency Repairs",
    kind: "source",
    group: "source",
    civs: ["Holy Roman Empire", "Order of the Dragon"],
    source: "Town Center Influence",
    icon: "assets/images/abilities/ability-emergency-repairs-1.png",
    description:
      "Regenerates 150 HP/s for 20 seconds after taking damage. 75 second cooldown.",
    defaultActive: false,
    effects: {
      repairRate: 150,
      repairDuration: 20,
      repairCooldown: 75,
      autoTrigger: true,
    },
  },
  townCenterInfluence: {
    id: "townCenterInfluence",
    name: "Town Center Influence",
    kind: "source",
    group: "source",
    civs: ["Holy Roman Empire", "Order of the Dragon"],
    icon: "assets/images/abilities/ability-emergency-repairs-1.png",
    description:
      "Source aura that grants Emergency Repairs to eligible nearby buildings. Shown for reference only.",
    defaultActive: false,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  elzbachInfluence: {
    id: "elzbachInfluence",
    name: "Elzbach Palace Influence",
    kind: "source",
    group: "source",
    civs: ["Holy Roman Empire", "Order of the Dragon"],
    source: "Elzbach Palace",
    icon: "assets/images/buildings/elzbach-palace.png",
    description: "-25% incoming damage before armor.",
    defaultActive: false,
    effects: { damageResistancePct: 25 },
  },
  networkOfCastles: {
    id: "networkOfCastles",
    name: "Network of Castles",
    kind: "source",
    group: "source",
    civs: ["English"],
    icon: "assets/images/abilities/ability-network-of-castles-1.png",
    description:
      "English aura shown for reference only in direct building duels.",
    mode: "level",
    defaultLevel: 0,
    displayOnly: true,
    simulates: false,
    labels: ["Network: Off", "Network: +20%", "Citadels: +30%"],
    icons: [
      "assets/images/abilities/ability-network-of-castles-1.png",
      "assets/images/abilities/ability-network-of-castles-1.png",
      "assets/images/abilities/ability-network-of-citadels-1.png",
    ],
    effectsByLevel: [{}, { attackSpeedPct: 20 }, { attackSpeedPct: 30 }],
  },
  redPalaceInfluence: {
    id: "redPalaceInfluence",
    name: "Red Palace Influence",
    kind: "source",
    group: "source",
    civs: ["French", "Jeanne d'Arc"],
    source: "Red Palace",
    icon: "assets/images/buildings/red-palace.png",
    description: "Unlocks a free Arbalest Emplacement on this building.",
    defaultActive: false,
    effects: { lockedEmplacementsAdd: ["Arbalest Emplacement"] },
  },
  redPalaceSourceAura: {
    id: "redPalaceSourceAura",
    name: "Red Palace Aura",
    kind: "source",
    group: "source",
    civs: ["French", "Jeanne d'Arc"],
    icon: "assets/images/buildings/red-palace.png",
    description:
      "Activates Arbalest Emplacements on allied Keeps and Town Centers. Shown for reference only.",
    defaultActive: true,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  extensiveFortifications: {
    id: "extensiveFortifications",
    name: "Extensive Fortifications",
    kind: "tech",
    civs: ["Ottomans"],
    icon: "assets/images/technologies/great-bombard-emplacement-4.png",
    description:
      "+1 garrison arrow damage, +2 bonus vs Heavy. Cost reduction is display-only.",
    defaultActive: false,
    effects: { garrisonArrowDmgAdd: 1, garrisonArrowBonusAdd: { Heavy: 2 } },
  },
  extraMaterials: {
    id: "extraMaterials",
    name: "Extra Materials",
    kind: "ability",
    civs: ["Chinese"],
    icon: "assets/images/abilities/ability-extra-materials-1.png",
    description:
      "Auto-repairs nearby walls and gates. Shown for reference only in building duels.",
    defaultActive: false,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  villageFortresses: {
    id: "villageFortresses",
    name: "Village Fortresses",
    kind: "ability",
    civs: ["Delhi Sultanate"],
    icon: "assets/images/technologies/village-fortresses-3.png",
    description:
      "Keeps function like Town Centers. Shown for reference only in building duels.",
    defaultActive: false,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  medicalCenters: {
    id: "medicalCenters",
    name: "Medical Centers",
    kind: "ability",
    civs: ["Abbasid Dynasty"],
    icon: "assets/images/abilities/ability-medical-centers-1.png",
    description:
      "Heals nearby units. Shown for reference only in building duels.",
    defaultActive: false,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  slowBurningDefenses: {
    id: "slowBurningDefenses",
    name: "Slow-Burning Defenses",
    kind: "tech",
    civs: ["Delhi Sultanate"],
    icon: "assets/images/technologies/slow-burning-defenses-4.png",
    description: "+10 fire armor.",
    defaultActive: false,
    effects: { fireArmorAdd: 10 },
  },
  enlistmentIncentives: {
    id: "enlistmentIncentives",
    name: "Enlistment Incentives",
    kind: "ability",
    civs: ["French"],
    icon: "assets/images/technologies/enlistment-incentives-4.png",
    description:
      "Improves the French Keep influence cost reduction. Shown for reference only.",
    defaultActive: false,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  garrisonedRelic: {
    id: "garrisonedRelic",
    name: "Garrisoned Relic",
    kind: "ability",
    civs: ["Holy Roman Empire", "Order of the Dragon"],
    icon: "assets/images/abilities/ability-relic-garrisoned-1.png",
    description: "+25% attack, +20% range, +25% ranged/fire armor.",
    defaultActive: false,
    effects: {
      baseArrowDmgPct: 25,
      garrisonArrowDmgPct: 25,
      rangePct: 20,
      rangedArmorPct: 25,
      fireArmorPct: 25,
    },
  },
  fortOfTheHuntressVenom: {
    id: "fortOfTheHuntressVenom",
    name: "Poison Arrows",
    kind: "ability",
    civs: ["Malians"],
    icon: "assets/images/technologies/poisoned-arrows-3.png",
    description: "Building projectiles apply poison for 3 damage over 6 seconds.",
    defaultActive: true,
    effects: { poisonTotalDamage: 3, poisonDuration: 6 },
  },
  huntressStealthAura: {
    id: "huntressStealthAura",
    name: "Huntress Aura",
    kind: "ability",
    civs: ["Malians"],
    icon: "assets/images/abilities/ability-huntress-stealth-1.png",
    description:
      "Nearby allied infantry can enter stealth. Shown for reference only.",
    defaultActive: true,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  whiteTowerWorkRate: {
    id: "whiteTowerWorkRate",
    name: "White Tower Work Rate",
    kind: "ability",
    civs: ["English"],
    icon: "assets/images/buildings/the-white-tower-2.png",
    description:
      "Works 75% faster. Shown for reference only in building duels.",
    defaultActive: true,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  aHouseUnified: {
    id: "aHouseUnified",
    name: "A House Unified",
    kind: "ability",
    civs: ["House of Lancaster"],
    icon: "assets/images/abilities/ability-lancaster-castle-1.png",
    description:
      "Grants Earl's Guard and boosts Earl's Guard / Demilancer damage. Shown for reference only.",
    defaultActive: true,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  militaryAcademy: {
    id: "militaryAcademy",
    name: "Military Academy",
    kind: "tech",
    civs: ["English", "Jeanne d'Arc"],
    icon: "assets/images/technologies/military-academy-3.png",
    description:
      "+33% creation speed. Shown for reference only in building duels.",
    defaultActive: false,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  tradeProtection: {
    id: "tradeProtection",
    name: "Trade Protection",
    kind: "source",
    group: "source",
    civs: ["Ottomans"],
    icon: "assets/images/buildings/sea-gate-castle-3.png",
    description:
      "Trader aura shown for reference only in direct building duels.",
    defaultActive: true,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  keepInfluenceFrench: {
    id: "keepInfluenceFrench",
    name: "Keep Influence",
    kind: "source",
    group: "source",
    civs: ["French"],
    icon: "assets/images/abilities/ability-keep-influence-1.png",
    description:
      "French unit-cost aura shown for reference only in building duels.",
    defaultActive: true,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  castleOfTheCrowAura: {
    id: "castleOfTheCrowAura",
    name: "Castle of the Crow Aura",
    kind: "source",
    group: "source",
    civs: ["Sengoku Daimyo"],
    icon: "assets/images/abilities/ability-castle-of-the-crow-aura-1.png",
    description:
      "Nearby ranged siege gets +10% damage and +1 range. Shown for reference only.",
    defaultActive: true,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  treasureCaravans: {
    id: "treasureCaravans",
    name: "Treasure Caravans",
    kind: "ability",
    civs: ["Japanese"],
    icon: "assets/images/abilities/ability-treasure-caravans-1.png",
    description:
      "Economic landmark effect shown for reference only in building duels.",
    defaultActive: true,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  treasureTowers: {
    id: "treasureTowers",
    name: "Treasure Towers",
    kind: "ability",
    civs: ["Knights Templar"],
    icon: "assets/images/abilities/ability-treasure-towers-1.png",
    description:
      "Gold-generation aura shown for reference only in building duels.",
    defaultActive: false,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  gionFestival: {
    id: "gionFestival",
    name: "Gion Festival",
    kind: "tech",
    civs: ["Japanese"],
    icon: "assets/images/technologies/gion-festival-4.png",
    description:
      "+2 line of sight. Shown for reference only in building duels.",
    defaultActive: false,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  desertCitadels: {
    id: "desertCitadels",
    name: "Desert Citadels",
    kind: "ability",
    civs: ["Knights Templar"],
    icon: "assets/images/technologies/desert-citadels-2.png",
    description:
      "Improves the Desert Outposts aura. Shown for reference only in building duels.",
    defaultActive: false,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  ironClamps: {
    id: "ironClamps",
    name: "Iron Clamps",
    kind: "tech",
    civs: ["Knights Templar"],
    icon: "assets/images/technologies/iron-clamps-4.png",
    description: "-20% damage from gunpowder units.",
    defaultActive: false,
    effects: {
      conditionalDamageResistance: [{ tags: ["Gunpowder"], pct: 20 }],
    },
  },
  appointGovernor: {
    id: "appointGovernor",
    name: "Appoint Governor",
    kind: "ability",
    civs: ["Tughlaq Dynasty"],
    icon: "assets/images/buildings/tughlaqabad-fort-2.png",
    description:
      "Governor selection and economy bonuses shown for reference only.",
    defaultActive: true,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  shahiWalls: {
    id: "shahiWalls",
    name: "Shahi Walls",
    kind: "tech",
    civs: ["Tughlaq Dynasty"],
    icon: "assets/images/technologies/red-brick-bastions-4.png",
    description:
      "+1500 HP, +2 attack, +1 range, +1 base projectile, +3 fire armor.",
    defaultActive: false,
    effects: {
      hpAdd: 1500,
      baseArrowDmgAdd: 2,
      garrisonArrowDmgAdd: 2,
      rangeAdd: 1,
      baseArrowsAdd: 1,
      fireArmorAdd: 3,
    },
  },
  redBrickBastions: {
    id: "redBrickBastions",
    name: "Red Brick Bastions",
    kind: "tech",
    civs: ["Tughlaq Dynasty"],
    icon: "assets/images/technologies/red-brick-bastions-4.png",
    description:
      "+1500 HP, +2 attack, +1 range, +1 base projectile, +5 fire armor.",
    defaultActive: false,
    effects: {
      hpAdd: 1500,
      baseArrowDmgAdd: 2,
      garrisonArrowDmgAdd: 2,
      rangeAdd: 1,
      baseArrowsAdd: 1,
      fireArmorAdd: 5,
    },
  },
  tughlaqabadFortBenefactor: {
    id: "tughlaqabadFortBenefactor",
    name: "Tughlaqabad Fort Benefactor",
    kind: "tech",
    civs: ["Tughlaq Dynasty"],
    icon: "assets/images/buildings/tughlaqabad-fort-2.png",
    description: "+1500 HP. Governor unlock is shown for reference only.",
    defaultActive: false,
    effects: { hpAdd: 1500 },
  },
  curseOfAuliya: {
    id: "curseOfAuliya",
    name: "Curse of Auliya",
    kind: "ability",
    civs: ["Tughlaq Dynasty"],
    icon: "assets/images/technologies/curse-of-auliya-1.png",
    description: "Attackers targeting the fort suffer -30% attack speed.",
    defaultActive: false,
    effects: { attackerAttackSpeedSlowPct: 30 },
  },
  tughlaqabadFortOverwatch: {
    id: "tughlaqabadFortOverwatch",
    name: "Tughlaqabad Fort Overwatch",
    kind: "source",
    group: "source",
    civs: ["Tughlaq Dynasty"],
    icon: "assets/images/abilities/ability-tughlaqabad-fort-overwatch-1.png",
    description:
      "Dock support aura shown for reference only in direct building duels.",
    defaultActive: false,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  gloriousCharge: {
    id: "gloriousCharge",
    name: "Glorious Charge",
    kind: "ability",
    civs: ["Golden Horde"],
    icon: "assets/images/abilities/ability-glorious-charge-1.png",
    description: "Fortified Outpost active aura shown for reference only.",
    defaultActive: false,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  woodenFortressInfluence: {
    id: "woodenFortressInfluence",
    name: "Wooden Fortress Influence",
    kind: "source",
    group: "source",
    civs: ["Rus"],
    icon: "assets/images/buildings/wooden-fortress-1.png",
    description:
      "Wood drop-off aura shown for reference only in building duels.",
    defaultActive: true,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  fortifiedOutpostInfluence: {
    id: "fortifiedOutpostInfluence",
    name: "Fortified Outpost Edicts",
    kind: "source",
    group: "source",
    civs: ["Golden Horde"],
    icon: "assets/images/buildings/fortified-outpost-1.png",
    description: "Golden Tent edict interactions shown for reference only.",
    defaultActive: true,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
  tollOutpostAura: {
    id: "tollOutpostAura",
    name: "Taxation Aura",
    kind: "source",
    group: "source",
    civs: ["Malians"],
    icon: "assets/images/buildings/toll-outpost-1.png",
    description: "Trade tax aura shown for reference only in building duels.",
    defaultActive: true,
    displayOnly: true,
    simulates: false,
    effects: {},
  },
};

function buildingEnhancement(id, overrides = {}) {
  const base = BUILDING_ENHANCEMENT_DEFS[id];
  return {
    ...cloneValue(base),
    ...cloneValue(overrides),
  };
}

function makeBuilding(base, enhancements = [], overrides = {}) {
  return {
    meleeArmor: 0,
    baseAttackType: "ranged",
    garrisonAttackType: "ranged",
    baseArrowBonus: { Ship: 10 },
    garrisonArrowBonus: { Ship: 10 },
    emplacements: [],
    lockedEmplacements: [],
    emplacementMode: "toggle",
    civs: [],
    enhancements: enhancements.map((entry) =>
      typeof entry === "string" ? buildingEnhancement(entry) : cloneValue(entry)
    ),
    ...cloneValue(base),
    ...cloneValue(overrides),
  };
}

const TOWN_CENTER_ENHANCEMENTS = [
  "courtArchitects",
  "arrowUpgrades",
  "textiles",
  "bancoRepairs",
  "daimyoTownCenter",
  "gionFestival",
  "medicalCenters",
  "slateAndStoneConstruction",
  "houseOfWisdomInfluence",
  "emergencyRepairs",
  "redPalaceInfluence",
  "townCenterInfluence",
  "networkOfCastles",
  "extensiveFortifications",
];

const OUTPOST_ENHANCEMENTS = [
  "courtArchitects",
  "arrowUpgrades",
  "fortifyOutpost",
  "reinforcedDefenses",
  "slateAndStoneConstruction",
  "houseOfWisdomInfluence",
  "divineDefense",
  "praesidiumInfluence",
  "emergencyRepairs",
  "elzbachInfluence",
  "garrisonedRelic",
  "networkOfCastles",
  "extensiveFortifications",
  "paxMongolica",
  "extraMaterials",
];

const KEEP_ENHANCEMENTS = [
  "courtArchitects",
  "arrowUpgrades",
  "fortificationsMacedonian",
  "sharpeningStonesMacedonian",
  "boilingOil",
  "extraMaterials",
  "slowBurningDefenses",
  "villageFortresses",
  "networkOfCastles",
  "enlistmentIncentives",
  "reinforcedDefenses",
  "slateAndStoneConstruction",
  "medicalCenters",
  "emergencyRepairs",
  "divineDefense",
  "houseOfWisdomInfluence",
  "praesidiumInfluence",
  "elzbachInfluence",
  "garrisonedRelic",
  "redPalaceInfluence",
  "extensiveFortifications",
];

export const BUILDINGS = {
  "Capital Town Center": makeBuilding(
    {
      hp: 7000,
      rangedArmor: 50,
      fireArmor: 0,
      garrisonMax: 15,
      range: 8,
      baseArrows: 1,
      baseArrowDmg: 8,
      baseArrowRate: 1.88,
      garrisonArrowDmg: 6,
      garrisonArrowRate: 3.88,
    },
    [
      ...TOWN_CENTER_ENHANCEMENTS,
      "englishCapitalArrows",
      "templarCapitalHp",
      "chineseCapitalHandcannon",
    ]
  ),
  "Town Center": makeBuilding(
    {
      hp: 2500,
      rangedArmor: 50,
      fireArmor: 0,
      garrisonMax: 8,
      range: 6,
      baseArrows: 0,
      baseArrowDmg: 0,
      baseArrowRate: 0,
      garrisonArrowDmg: 6,
      garrisonArrowRate: 3.88,
    },
    TOWN_CENTER_ENHANCEMENTS
  ),
  Outpost: makeBuilding(
    {
      hp: 750,
      rangedArmor: 50,
      fireArmor: 0,
      garrisonMax: 5,
      range: 6,
      baseArrows: 0,
      baseArrowDmg: 0,
      baseArrowRate: 0,
      garrisonArrowDmg: 6,
      garrisonArrowRate: 3.88,
      emplacements: [
        "Arrowslits",
        "Handcannon Slits",
        "Springald Emplacement",
        "Mangonel Emplacement",
        "Cannon Emplacement",
      ],
      emplacementMode: "radio",
    },
    OUTPOST_ENHANCEMENTS
  ),
  "Toll Outpost": makeBuilding(
    {
      hp: 750,
      rangedArmor: 50,
      fireArmor: 0,
      garrisonMax: 5,
      range: 6,
      baseArrows: 0,
      baseArrowDmg: 0,
      baseArrowRate: 0,
      garrisonArrowDmg: 6,
      garrisonArrowRate: 3.88,
      emplacements: [
        "Arrowslits",
        "Javelin Emplacement",
        "Springald Emplacement",
        "Cannon Emplacement",
      ],
      emplacementMode: "radio",
      civs: ["Malians"],
    },
    ["courtArchitects", "arrowUpgrades", "fortifyOutpost", "tollOutpostAura"]
  ),
  "Wooden Fortress": makeBuilding(
    {
      hp: 1750,
      rangedArmor: 50,
      fireArmor: 0,
      garrisonMax: 8,
      range: 6,
      baseArrows: 0,
      baseArrowDmg: 0,
      baseArrowRate: 0,
      garrisonArrowDmg: 6,
      garrisonArrowRate: 1.88,
      emplacements: ["Arrowslits", "Springald Emplacement"],
      emplacementMode: "toggle",
      civs: ["Rus"],
    },
    [
      "courtArchitects",
      "arrowUpgrades",
      "castleTurret",
      "castleWatch",
      "woodenFortressInfluence",
    ]
  ),
  "Fortified Outpost": makeBuilding(
    {
      hp: 1700,
      rangedArmor: 50,
      fireArmor: 0,
      garrisonMax: 5,
      range: 6,
      baseArrows: 0,
      baseArrowDmg: 0,
      baseArrowRate: 0,
      garrisonArrowDmg: 6,
      garrisonArrowRate: 3.88,
      emplacements: [
        "Arrowslits",
        "Springald Emplacement",
        "Cannon Emplacement",
      ],
      emplacementMode: "radio",
      civs: ["Golden Horde"],
    },
    [
      "courtArchitects",
      "arrowUpgrades",
      "earthenCoreWalls",
      "gloriousCharge",
      "fortifiedOutpostInfluence",
    ]
  ),
  Keep: makeBuilding(
    {
      hp: 5000,
      rangedArmor: 50,
      fireArmor: 6,
      garrisonMax: 15,
      range: 8,
      baseArrows: 3,
      baseArrowDmg: 12,
      baseArrowRate: 0.5,
      garrisonArrowDmg: 10,
      garrisonArrowRate: 2.62,
      emplacements: [
        "Springald Emplacement",
        "Cannon Emplacement",
        "Mangonel Emplacement",
        "Great Bombard Emplacement",
      ],
      civs: [],
    },
    KEEP_ENHANCEMENTS
  ),
  Castle: makeBuilding(
    {
      hp: 5500,
      rangedArmor: 50,
      fireArmor: 5,
      garrisonMax: 15,
      range: 9,
      baseArrows: 1,
      baseArrowDmg: 80,
      baseArrowRate: 4.125,
      baseAttackType: "siege",
      baseArrowBonus: { Human: 110, Infantry: 110, Cavalry: 110, Ship: 330 },
      garrisonArrowDmg: 10,
      garrisonArrowRate: 2.62,
      emplacements: ["Springald Emplacement", "Cannon Emplacement"],
      civs: ["Japanese", "Sengoku Daimyo"],
    },
    [
      "courtArchitects",
      "arrowUpgrades",
      "boilingOil",
      "gionFestival",
    ]
  ),
  Fortress: makeBuilding(
    {
      hp: 5000,
      rangedArmor: 50,
      fireArmor: 6,
      garrisonMax: 15,
      range: 8,
      baseArrows: 3,
      baseArrowDmg: 12,
      baseArrowRate: 0.5,
      garrisonArrowDmg: 10,
      garrisonArrowRate: 2.62,
      emplacements: ["Springald Emplacement", "Trebuchet Emplacement"],
      civs: ["Knights Templar"],
    },
    [
      "courtArchitects",
      "arrowUpgrades",
      "boilingOil",
      "desertCitadels",
      "treasureTowers",
      "ironClamps",
    ]
  ),
  "Tughlaqabad Fort": makeBuilding(
    {
      hp: 2000,
      rangedArmor: 50,
      fireArmor: 0,
      garrisonMax: 10,
      range: 6,
      baseArrows: 2,
      baseArrowDmg: 10,
      baseArrowRate: 0.5,
      garrisonArrowDmg: 6,
      garrisonArrowRate: 2.62,
      emplacements: ["Springald Emplacement", "Cannon Emplacement"],
      civs: ["Tughlaq Dynasty"],
    },
    [
      "courtArchitects",
      "arrowUpgrades",
      "appointGovernor",
      "shahiWalls",
      "redBrickBastions",
      "tughlaqabadFortBenefactor",
      "curseOfAuliya",
      "tughlaqabadFortOverwatch",
    ]
  ),
  "The White Tower": makeBuilding(
    {
      hp: 5000,
      rangedArmor: 50,
      fireArmor: 6,
      garrisonMax: 20,
      range: 8,
      baseArrows: 3,
      baseArrowDmg: 12,
      baseArrowRate: 0.5,
      garrisonArrowDmg: 10,
      garrisonArrowRate: 2.62,
      emplacements: ["Springald Emplacement", "Cannon Emplacement"],
      civs: ["English", "House of Lancaster"],
    },
    [
      "courtArchitects",
      "arrowUpgrades",
      "boilingOil",
      buildingEnhancement("networkOfCastles", { defaultLevel: 1 }),
      "whiteTowerWorkRate",
      "aHouseUnified",
      "militaryAcademy",
    ]
  ),
  "Berkshire Palace": makeBuilding(
    {
      hp: 6500,
      rangedArmor: 50,
      fireArmor: 6,
      garrisonMax: 20,
      range: 14.5,
      baseArrows: 3,
      baseArrowDmg: 14,
      baseArrowRate: 0.5,
      garrisonArrowDmg: 12,
      garrisonArrowRate: 2.62,
      emplacements: ["Springald Emplacement", "Cannon Emplacement"],
      civs: ["English", "House of Lancaster"],
    },
    [
      "courtArchitects",
      "arrowUpgrades",
      "boilingOil",
      buildingEnhancement("networkOfCastles", { defaultLevel: 1 }),
      "aHouseUnified",
    ]
  ),
  "Red Palace": makeBuilding(
    {
      hp: 5000,
      rangedArmor: 50,
      fireArmor: 6,
      garrisonMax: 15,
      range: 10,
      baseArrows: 2,
      baseArrowDmg: 60,
      baseArrowRate: 1.5,
      baseArrowBonus: { Ship: 50 },
      garrisonArrowDmg: 60,
      garrisonArrowRate: 1.5,
      garrisonArrowBonus: { Ship: 50 },
      emplacements: ["Springald Emplacement", "Cannon Emplacement"],
      civs: ["French", "Jeanne d'Arc"],
    },
    [
      "courtArchitects",
      "arrowUpgrades",
      "boilingOil",
      "enlistmentIncentives",
      "keepInfluenceFrench",
      "redPalaceSourceAura",
    ]
  ),
  "Elzbach Palace": makeBuilding(
    {
      hp: 7500,
      rangedArmor: 50,
      fireArmor: 6,
      garrisonMax: 20,
      range: 8,
      baseArrows: 3,
      baseArrowDmg: 12,
      baseArrowRate: 0.5,
      garrisonArrowDmg: 10,
      garrisonArrowRate: 2.62,
      emplacements: ["Springald Emplacement", "Cannon Emplacement"],
      civs: ["Holy Roman Empire", "Order of the Dragon"],
    },
    [
      "courtArchitects",
      "arrowUpgrades",
      "boilingOil",
      "slateAndStoneConstruction",
      "emergencyRepairs",
      "garrisonedRelic",
      buildingEnhancement("elzbachInfluence", { defaultActive: true }),
    ]
  ),
  "Fort of the Huntress": makeBuilding(
    {
      hp: 5000,
      rangedArmor: 50,
      fireArmor: 6,
      garrisonMax: 15,
      range: 8,
      baseArrows: 3,
      baseArrowDmg: 15,
      baseArrowRate: 0.5,
      garrisonArrowDmg: 13,
      garrisonArrowRate: 2.62,
      emplacements: ["Springald Emplacement", "Cannon Emplacement"],
      civs: ["Malians"],
    },
    [
      "courtArchitects",
      "arrowUpgrades",
      "boilingOil",
      "fortOfTheHuntressVenom",
      "huntressStealthAura",
    ]
  ),
  "Sea Gate Castle": makeBuilding(
    {
      hp: 5000,
      rangedArmor: 50,
      fireArmor: 6,
      garrisonMax: 15,
      range: 8,
      baseArrows: 3,
      baseArrowDmg: 12,
      baseArrowRate: 0.5,
      garrisonArrowDmg: 10,
      garrisonArrowRate: 2.62,
      emplacements: ["Springald Emplacement"],
      lockedEmplacements: ["Great Bombard Emplacement"],
      civs: ["Ottomans"],
    },
    ["courtArchitects", "arrowUpgrades", "boilingOil", "tradeProtection"]
  ),
  "Castle of the Crow": makeBuilding(
    {
      hp: 5500,
      rangedArmor: 50,
      fireArmor: 6,
      garrisonMax: 15,
      range: 9,
      baseArrows: 1,
      baseArrowDmg: 80,
      baseArrowRate: 4.125,
      baseAttackType: "siege",
      baseArrowBonus: { Human: 110, Infantry: 110, Cavalry: 110, Ship: 330 },
      garrisonArrowDmg: 10,
      garrisonArrowRate: 2.62,
      emplacements: ["Springald Emplacement", "Cannon Emplacement"],
      civs: ["Japanese", "Sengoku Daimyo"],
    },
    [
      "courtArchitects",
      "arrowUpgrades",
      "boilingOil",
      "gionFestival",
      "castleOfTheCrowAura",
      "treasureCaravans",
    ]
  ),
};

const BUILDING_DETAIL_DATA = {
  "Capital Town Center": {
    type: "Economy and Population Building / Landmark",
    age: "Starting building",
    costText: "Starts the match built",
    buildTimeText: "Starts built",
    size: "4 x 4 tiles",
    summary:
      "The Capital Town Center is the starting landmark around which most civilizations expand. It trains Villagers and Scouts, drops off all resources, provides population, and automatically fires arrowslits even when ungarrisoned.",
    specialNotes: [
      "Acts as the starting landmark in random map games.",
      "Automatically fires arrowslits even without a garrison.",
      "Can detect stealth and disguise.",
      "Knights Templar use the Templar Headquarters variant.",
    ],
    trainableUnits: ["Villager", "Scout"],
  },
  "Town Center": {
    type: "Economy and Population Building",
    age: "Feudal Age",
    cost: { wood: 400, stone: 350 },
    buildTime: 150,
    size: "4 x 4 tiles",
    summary:
      "The Town Center is the core economic building for every civilization. It trains and improves Villagers, drops off all resources, and provides 10 population.",
    specialNotes: [
      "Secondary Town Centers do not auto-fire unless garrisoned.",
      "Does not detect stealth or disguise.",
      "Many civilizations add unique influence, trainable units, or special upgrades here.",
    ],
    trainableUnits: ["Villager", "Scout"],
  },
  Outpost: {
    type: "Tower / Defensive Building",
    age: "Dark Age",
    cost: { wood: 100 },
    buildTime: 60,
    size: "2 x 2 tiles",
    summary:
      "The Outpost is a defensive structure with extensive line of sight and stealth detection. It cannot attack by default, but gains projectiles when garrisoned or upgraded with emplacements.",
    specialNotes: [
      "Detects stealth and disguise.",
      "Does not attack until units are garrisoned or a weapon emplacement is added.",
    ],
  },
  "Toll Outpost": {
    type: "Tower / Defensive Building",
    age: "Dark Age",
    cost: { wood: 100 },
    buildTime: 60,
    size: "2 x 2 tiles",
    summary:
      "The Toll Outpost is the Malian Outpost variant. It is statistically identical to a normal Outpost, but adds the Taxation Aura for passing Traders and Trade Ships.",
    specialNotes: [
      "Malian Outpost replacement.",
      "Taxation Aura can generate bonus gold, and wood from Trade Ships, from passing trade units.",
    ],
  },
  "Wooden Fortress": {
    type: "Defensive Building",
    age: "Dark Age",
    cost: { wood: 175 },
    buildTime: 60,
    size: "2 x 2 tiles",
    summary:
      "The Wooden Fortress is the Rus Outpost replacement. It is sturdier than a standard Outpost, has more garrison space, and projects an influence that boosts nearby wood drop-offs.",
    specialNotes: [
      "Rus Outpost replacement.",
      "Wooden Fortress Influence increases nearby wood drop-off by 20%.",
      "Can research both Arrowslits and Springald Emplacement at the same time.",
    ],
  },
  "Fortified Outpost": {
    type: "Tower / Defensive Building",
    age: "Dark Age",
    cost: { wood: 150, stone: 50 },
    buildTime: 60,
    size: "3 x 3 tiles",
    summary:
      "The Fortified Outpost is the Golden Horde Outpost replacement. It is a larger, tougher tower that can attack while garrisoned and supports Golden Horde-specific edicts and techs.",
    specialNotes: [
      "Golden Horde Outpost replacement.",
      "Supports Golden Tent edicts and Fortified Outpost-specific techs such as Earthen Core Walls and Glorious Charge.",
    ],
  },
  Keep: {
    type: "Defensive structure",
    age: "Castle Age",
    cost: { stone: 900 },
    buildTime: 180,
    size: "4 x 4 tiles",
    summary:
      "The Keep is the standard late-game defensive structure for most civilizations. It has strong base arrowslits, high durability, and access to multiple emplacements and defensive techs.",
    specialNotes: [
      "Fires arrows without needing a garrison.",
      "Can be upgraded with emplacements and civilization-specific keep technologies.",
    ],
  },
  Castle: {
    type: "Defensive structure",
    age: "Imperial Age",
    cost: { wood: 300, stone: 900 },
    buildTime: 180,
    size: "4 x 4 tiles",
    summary:
      "The Castle is the Japanese and Sengoku Daimyo Keep replacement. It trades the standard Keep arrow barrage for a single powerful rocket attack and becomes available in the Imperial Age.",
    specialNotes: [
      "Japanese and Sengoku Daimyo Keep replacement.",
      "Built-in rocket attack does not need a garrison.",
      "Sengoku Daimyo Castles can benefit from Castle of the Crow Aura.",
    ],
  },
  Fortress: {
    type: "Defensive Landmark",
    age: "Feudal Age",
    cost: { gold: 300, stone: 600 },
    buildTime: 180,
    size: "4 x 4 tiles",
    summary:
      "The Fortress is the Knights Templar landmark replacement for the Keep. It arrives in Feudal Age, costs less than a normal landmark, and adds several unique defensive and influence effects.",
    specialNotes: [
      "Knights Templar Keep replacement that can be permanently destroyed.",
      "Desert Outposts improves nearby ranged-unit range and also affects melee torch range.",
      "Each Fortress increases the Pilgrim travel cap by 1.",
    ],
  },
  "Tughlaqabad Fort": {
    type: "Defensive structure",
    age: "Feudal Age",
    cost: { stone: 400 },
    buildTime: 135,
    size: "4 x 4 tiles",
    summary:
      "The Tughlaqabad Fort is the Tughlaq Dynasty Keep replacement. It arrives in Feudal Age, attacks like a fortified tower, and can appoint Governors to grant additional bonuses.",
    specialNotes: [
      "Tughlaq Dynasty Keep replacement.",
      "Can appoint Governors for different bonuses.",
      "Supports fort-specific upgrades such as Shahi Walls, Red Brick Bastions, and Curse of Auliya.",
    ],
    trainableUnits: ["Worker Elephant"],
  },
  "The White Tower": {
    type: "Defensive Landmark",
    age: "Feudal Age",
    cost: { food: 1200, gold: 600 },
    buildTime: 220,
    size: "4 x 4 tiles",
    summary:
      "The White Tower is an English and House of Lancaster defensive landmark that acts as an improved Keep. It has increased garrison space, keeps all standard Keep techs, and gives the English an early military anchor on Castle-up.",
    specialNotes: [
      "English version works 75% faster.",
      "English gain Network of Castles / Network of Citadels coverage from it.",
      "House of Lancaster also gains A House Unified on completion.",
    ],
  },
  "Berkshire Palace": {
    type: "Defensive Landmark",
    age: "Castle Age",
    cost: { food: 2400, gold: 1200 },
    buildTime: 250,
    size: "4 x 4 tiles",
    summary:
      "The Berkshire Palace is an English and House of Lancaster defensive landmark that acts as an improved Keep with more hit points, stronger incendiary arrows, and extreme 14.5 range on all of its projectiles.",
    specialNotes: [
      "All of its projectiles and emplacements have 14.5 range.",
      "English gain Network of Castles / Network of Citadels coverage from it.",
      "House of Lancaster raises A House Unified's max damage bonus to 6 and grants 3 Earl's Guard on completion.",
    ],
  },
  "Red Palace": {
    type: "Defensive Landmark",
    age: "Castle Age",
    cost: { food: 2400, gold: 1200 },
    buildTime: 250,
    size: "4 x 4 tiles",
    summary:
      "The Red Palace is a French and Jeanne d'Arc defensive landmark that acts as a Keep with high-damage arbalest attacks instead of normal arrowslits.",
    specialNotes: [
      "Uses arbalest attacks instead of standard Keep arrowslits.",
      "Each garrisoned unit adds another arbalest shot.",
      "Unlocks Arbalest Emplacements on all French and Jeanne d'Arc Keeps and Town Centers.",
    ],
  },
  "Elzbach Palace": {
    type: "Defensive Landmark",
    age: "Castle Age",
    cost: { food: 2400, gold: 1200 },
    buildTime: 220,
    size: "4 x 4 tiles",
    summary:
      "The Elzbach Palace is a Holy Roman Empire and Order of the Dragon defensive landmark that acts as an improved Keep with 50% more hit points and a large defensive influence aura.",
    specialNotes: [
      "Acts as a Keep with 50% extra hit points.",
      "Elzbach Palace Influence makes buildings in range take 25% less damage.",
      "Its influence can extend Town Center Emergency Repairs coverage.",
    ],
  },
  "Fort of the Huntress": {
    type: "Defensive Landmark",
    age: "Castle Age",
    cost: { food: 2400, gold: 1200 },
    buildTime: 250,
    size: "4 x 4 tiles",
    summary:
      "The Fort of the Huntress is a Malian defensive landmark that acts as a Keep while adding poison to its projectiles and stealth support to nearby infantry.",
    specialNotes: [
      "Building projectiles deal 3 poison damage over 6 seconds in addition to direct damage.",
      "Nearby infantry gain stealth for 30 seconds.",
      "Musofadi Warriors and Musofadi Gunners gain First Strike from the aura.",
    ],
  },
  "Sea Gate Castle": {
    type: "Defensive Landmark",
    age: "Castle Age",
    cost: { food: 2400, gold: 1200 },
    buildTime: 250,
    size: "4 x 4 tiles",
    summary:
      "The Sea Gate Castle is an Ottoman defensive landmark that acts as a Keep with a free Great Bombard Emplacement and a powerful trade-support aura.",
    specialNotes: [
      "Comes with a free Great Bombard Emplacement.",
      "Ottoman Keeps nearby grant Traders and Trade Ships +30% movement speed and +8 armor.",
    ],
  },
  "Castle of the Crow": {
    type: "Defensive Landmark",
    age: "Castle Age",
    cost: { food: 2400, gold: 1200 },
    buildTime: 250,
    size: "4 x 4 tiles",
    summary:
      "The Castle of the Crow is a Japanese and Sengoku Daimyo defensive landmark that acts as a Castle and adds a unique economy or siege-support ability depending on the civilization.",
    specialNotes: [
      "Japanese version summons Treasure Caravans from neutral Trade Posts.",
      "Sengoku Daimyo version grants nearby ranged siege +10% damage and +1 range around Castles.",
      "Sengoku Daimyo also reduce Castle construction cost by 33%.",
    ],
  },
};

Object.entries(BUILDING_DETAIL_DATA).forEach(([name, detail]) => {
  if (BUILDINGS[name]) BUILDINGS[name].detail = cloneValue(detail);
});

// ========================================
// EMPLACEMENT DATA
// ========================================
export const EMPLACEMENTS = {
  Arrowslits: {
    dmg: 10,
    projectiles: 1,
    rate: 1.12,
    range: 7,
    type: "ranged",
    bonus: { Ship: 10 },
    civs: [],
  },
  "Handcannon Slits": {
    dmg: 25,
    projectiles: 1,
    rate: 3.12,
    range: 7,
    type: "ranged",
    bonus: { Ship: 10 },
    civs: ["Chinese", "Zhu Xi's Legacy"],
  },
  "Javelin Emplacement": {
    dmg: 12,
    projectiles: 1,
    rate: 1.12,
    range: 8,
    type: "ranged",
    bonus: { Ship: 10, Ranged: 4 },
    civs: ["Malians"],
  },
  "Springald Emplacement": {
    dmg: 40,
    projectiles: 1,
    rate: 3.88,
    range: 9,
    type: "siege",
    civs: [],
  },
  "Mangonel Emplacement": {
    dmg: 7,
    projectiles: 3,
    rate: 4.12,
    range: 8,
    type: "siege",
    civs: ["Byzantines", "Macedonian Dynasty"],
  },
  "Cannon Emplacement": {
    dmg: 70,
    projectiles: 1,
    rate: 5.88,
    range: 9.5,
    type: "siege",
    bonus: { Ship: 70 },
    civs: [],
  },
  "Great Bombard Emplacement": {
    dmg: 100,
    projectiles: 1,
    rate: 7.12,
    range: 10,
    type: "siege",
    bonus: { Ship: 100, Building: 200 },
    civs: ["Ottomans"],
  },
  "Arbalest Emplacement": {
    dmg: 40,
    projectiles: 1,
    rate: 1.5,
    range: 9.5,
    type: "ranged",
    bonus: { Ship: 50 },
    civs: ["French", "Jeanne d'Arc"],
  },
  "Trebuchet Emplacement": {
    dmg: 25,
    projectiles: 2,
    rate: 12.12,
    range: 18,
    type: "siege",
    bonus: { Ship: 100, Building: 250 },
    civs: ["Knights Templar"],
  },
  "Boiling Oil": {
    dmg: 30,
    projectiles: 1,
    rate: 9.62,
    range: 1.5,
    type: "siege",
    requiresContact: true,
    civs: [],
  },
  "Rocket Emplacement": {
    dmg: 80,
    projectiles: 1,
    rate: 4.125,
    range: 8,
    type: "siege",
    bonus: { Human: 110, Infantry: 110, Cavalry: 110, Ship: 330 },
    civs: ["Japanese"],
  },
};

export const TORCH_BY_AGE = { 2: 13, 3: 17, 4: 21 };
export const TORCH_ATTACK_SPEED = 2.15;

export const KIPCHAK_TRIPLE_SHOT = Object.freeze({
  extraArrows: 2,
  damageMultiplier: 0.3,
  extraBleedDpsPerArrow: 0.6,
  tickInterval: 1,
});

export const POISON_TICK_INTERVAL = 1; // 1 second ticks, same as bleed
