// ========================================
// Static combat data constants (no DOM dependencies)
// ========================================

// ========================================
// BUILDING DATA (Outpost, Keep, Town Center)
// ========================================
export const BUILDINGS = {
  // --- Town Centers ---
  "Capital Town Center": {
    hp: 7000,
    rangedArmor: 50,
    fireArmor: 0,
    garrisonMax: 15,
    range: 8,
    baseArrows: 1,
    baseArrowDmg: 8,
    baseArrowRate: 1.88,
    garrisonArrowDmg: 6,
    garrisonArrowRate: 3.88,
    techs: ["courtArchitects", "arrowUpgrades"],
    emplacements: [],
    civs: [],
  },
  "Town Center": {
    hp: 2400,
    rangedArmor: 50,
    fireArmor: 0,
    garrisonMax: 8,
    range: 6,
    baseArrows: 0,
    baseArrowDmg: 0,
    baseArrowRate: 0,
    garrisonArrowDmg: 6,
    garrisonArrowRate: 2.62,
    techs: ["courtArchitects", "arrowUpgrades"],
    emplacements: [],
    civs: [],
  },
  // --- Outposts ---
  Outpost: {
    hp: 750,
    rangedArmor: 50,
    fireArmor: 0,
    garrisonMax: 5,
    range: 6,
    baseArrows: 0,
    baseArrowDmg: 0,
    baseArrowRate: 0,
    garrisonArrowDmg: 6,
    garrisonArrowRate: 3.88,
    techs: ["courtArchitects", "arrowUpgrades", "fortifyOutpost"],
    emplacements: [
      "Arrowslits",
      "Handcannon Slits",
      "Springald Emplacement",
      "Mangonel Emplacement",
      "Cannon Emplacement",
    ],
    civs: [],
  },
  "Toll Outpost": {
    hp: 750,
    rangedArmor: 50,
    fireArmor: 0,
    garrisonMax: 5,
    range: 6,
    baseArrows: 0,
    baseArrowDmg: 0,
    baseArrowRate: 0,
    garrisonArrowDmg: 6,
    garrisonArrowRate: 3.88,
    techs: ["courtArchitects", "arrowUpgrades", "fortifyOutpost"],
    emplacements: [
      "Arrowslits",
      "Handcannon Slits",
      "Springald Emplacement",
      "Mangonel Emplacement",
      "Cannon Emplacement",
    ],
    civs: ["Malians"],
  },
  "Wooden Fortress": {
    hp: 1750,
    rangedArmor: 50,
    fireArmor: 0,
    garrisonMax: 8,
    range: 6,
    baseArrows: 0,
    baseArrowDmg: 0,
    baseArrowRate: 0,
    garrisonArrowDmg: 6,
    garrisonArrowRate: 1.88,
    techs: ["courtArchitects", "arrowUpgrades", "castleTurret"],
    emplacements: [
      "Arrowslits",
      "Handcannon Slits",
      "Springald Emplacement",
      "Mangonel Emplacement",
    ],
    civs: ["Rus", "Golden Horde"],
  },
  "Fortified Outpost": {
    hp: 1700,
    rangedArmor: 50,
    fireArmor: 0,
    garrisonMax: 5,
    range: 6,
    baseArrows: 0,
    baseArrowDmg: 0,
    baseArrowRate: 0,
    garrisonArrowDmg: 6,
    garrisonArrowRate: 3.88,
    techs: ["courtArchitects", "arrowUpgrades"],
    emplacements: [
      "Arrowslits",
      "Handcannon Slits",
      "Springald Emplacement",
      "Mangonel Emplacement",
      "Cannon Emplacement",
    ],
    civs: ["Golden Horde"],
  },
  // --- Keeps ---
  Keep: {
    hp: 5000,
    rangedArmor: 50,
    fireArmor: 6,
    garrisonMax: 15,
    range: 8,
    baseArrows: 3,
    baseArrowDmg: 12,
    baseArrowRate: 0.5,
    garrisonArrowDmg: 10,
    garrisonArrowRate: 2.62,
    techs: ["courtArchitects", "arrowUpgrades"],
    emplacements: [
      "Springald Emplacement",
      "Mangonel Emplacement",
      "Cannon Emplacement",
      "Great Bombard Emplacement",
      "Arbalest Emplacement",
    ],
    civs: [],
  },
  Castle: {
    hp: 5500,
    rangedArmor: 50,
    fireArmor: 5,
    garrisonMax: 15,
    range: 9,
    baseArrows: 1,
    baseArrowDmg: 80,
    baseArrowRate: 4.125,
    garrisonArrowDmg: 10,
    garrisonArrowRate: 2.62,
    techs: ["courtArchitects", "arrowUpgrades"],
    emplacements: [
      "Springald Emplacement",
      "Mangonel Emplacement",
      "Cannon Emplacement",
      "Great Bombard Emplacement",
      "Arbalest Emplacement",
    ],
    civs: ["Japanese", "Sengoku Daimyo"],
  },
  Fortress: {
    hp: 5000,
    rangedArmor: 50,
    fireArmor: 6,
    garrisonMax: 15,
    range: 8,
    baseArrows: 3,
    baseArrowDmg: 12,
    baseArrowRate: 0.5,
    garrisonArrowDmg: 10,
    garrisonArrowRate: 2.62,
    techs: ["courtArchitects", "arrowUpgrades"],
    emplacements: [
      "Springald Emplacement",
      "Mangonel Emplacement",
      "Cannon Emplacement",
      "Trebuchet Emplacement",
    ],
    civs: ["Knights Templar"],
  },
  "Tughlaqabad Fort": {
    hp: 2000,
    rangedArmor: 50,
    fireArmor: 0,
    garrisonMax: 10,
    range: 6,
    baseArrows: 2,
    baseArrowDmg: 10,
    baseArrowRate: 0.5,
    garrisonArrowDmg: 6,
    garrisonArrowRate: 2.62,
    techs: ["courtArchitects", "arrowUpgrades"],
    emplacements: [
      "Springald Emplacement",
      "Mangonel Emplacement",
      "Cannon Emplacement",
    ],
    civs: ["Tughlaq Dynasty"],
  },
  // --- Landmarks ---
  "The White Tower": {
    hp: 5000,
    rangedArmor: 50,
    fireArmor: 6,
    garrisonMax: 20,
    range: 8,
    baseArrows: 3,
    baseArrowDmg: 12,
    baseArrowRate: 0.5,
    garrisonArrowDmg: 10,
    garrisonArrowRate: 2.62,
    techs: ["courtArchitects", "arrowUpgrades"],
    emplacements: [
      "Springald Emplacement",
      "Mangonel Emplacement",
      "Cannon Emplacement",
      "Great Bombard Emplacement",
      "Arbalest Emplacement",
    ],
    civs: ["English", "House of Lancaster"],
  },
  "Berkshire Palace": {
    hp: 6500,
    rangedArmor: 50,
    fireArmor: 6,
    garrisonMax: 20,
    range: 14.5,
    baseArrows: 3,
    baseArrowDmg: 14,
    baseArrowRate: 0.5,
    garrisonArrowDmg: 12,
    garrisonArrowRate: 2.62,
    techs: ["courtArchitects", "arrowUpgrades"],
    emplacements: [
      "Springald Emplacement",
      "Mangonel Emplacement",
      "Cannon Emplacement",
      "Great Bombard Emplacement",
      "Arbalest Emplacement",
    ],
    civs: ["English", "House of Lancaster"],
  },
  "Red Palace": {
    hp: 5000,
    rangedArmor: 50,
    fireArmor: 6,
    garrisonMax: 15,
    range: 10,
    baseArrows: 2,
    baseArrowDmg: 60,
    baseArrowRate: 1.5,
    garrisonArrowDmg: 60,
    garrisonArrowRate: 1.5,
    techs: ["courtArchitects", "arrowUpgrades"],
    emplacements: [
      "Springald Emplacement",
      "Mangonel Emplacement",
      "Cannon Emplacement",
      "Great Bombard Emplacement",
      "Arbalest Emplacement",
    ],
    civs: ["French", "Jeanne d'Arc"],
  },
  "Elzbach Palace": {
    hp: 7500,
    rangedArmor: 50,
    fireArmor: 6,
    garrisonMax: 20,
    range: 8,
    baseArrows: 3,
    baseArrowDmg: 12,
    baseArrowRate: 0.5,
    garrisonArrowDmg: 10,
    garrisonArrowRate: 2.62,
    techs: ["courtArchitects", "arrowUpgrades"],
    emplacements: [
      "Springald Emplacement",
      "Mangonel Emplacement",
      "Cannon Emplacement",
      "Great Bombard Emplacement",
      "Arbalest Emplacement",
    ],
    civs: ["Holy Roman Empire", "Order of the Dragon"],
  },
  "Fort of the Huntress": {
    hp: 5000,
    rangedArmor: 50,
    fireArmor: 6,
    garrisonMax: 15,
    range: 8,
    baseArrows: 3,
    baseArrowDmg: 15,
    baseArrowRate: 0.5,
    garrisonArrowDmg: 13,
    garrisonArrowRate: 2.62,
    techs: ["courtArchitects", "arrowUpgrades"],
    emplacements: [
      "Springald Emplacement",
      "Mangonel Emplacement",
      "Cannon Emplacement",
      "Great Bombard Emplacement",
      "Arbalest Emplacement",
    ],
    civs: ["Rus", "Golden Horde"],
  },
  "Sea Gate Castle": {
    hp: 5000,
    rangedArmor: 50,
    fireArmor: 6,
    garrisonMax: 15,
    range: 8,
    baseArrows: 3,
    baseArrowDmg: 12,
    baseArrowRate: 0.5,
    garrisonArrowDmg: 10,
    garrisonArrowRate: 2.62,
    techs: ["courtArchitects", "arrowUpgrades"],
    emplacements: [
      "Springald Emplacement",
      "Mangonel Emplacement",
      "Cannon Emplacement",
      "Great Bombard Emplacement",
      "Arbalest Emplacement",
    ],
    civs: ["Japanese"],
  },
  "Castle of the Crow": {
    hp: 5500,
    rangedArmor: 50,
    fireArmor: 6,
    garrisonMax: 15,
    range: 9,
    baseArrows: 1,
    baseArrowDmg: 80,
    baseArrowRate: 4.125,
    garrisonArrowDmg: 10,
    garrisonArrowRate: 2.62,
    techs: ["courtArchitects", "arrowUpgrades"],
    emplacements: [
      "Springald Emplacement",
      "Mangonel Emplacement",
      "Cannon Emplacement",
      "Great Bombard Emplacement",
      "Arbalest Emplacement",
    ],
    civs: ["Japanese", "Sengoku Daimyo"],
  },
};

// ========================================
// EMPLACEMENT DATA
// ========================================
export const EMPLACEMENTS = {
  Arrowslits: {
    dmg: 10,
    projectiles: 1,
    rate: 1.12,
    range: 7,
    type: "ranged",
    civs: [],
  },
  "Handcannon Slits": {
    dmg: 25,
    projectiles: 1,
    rate: 3.12,
    range: 7,
    type: "ranged",
    civs: ["Chinese", "Zhu Xi's Legacy"],
  },
  "Springald Emplacement": {
    dmg: 40,
    projectiles: 1,
    rate: 3.88,
    range: 9,
    type: "ranged",
    civs: [],
  },
  "Mangonel Emplacement": {
    dmg: 7,
    projectiles: 3,
    rate: 4.12,
    range: 8,
    type: "siege",
    civs: ["Byzantines", "Macedonian Dynasty"],
  },
  "Cannon Emplacement": {
    dmg: 70,
    projectiles: 1,
    rate: 5.88,
    range: 9.5,
    type: "ranged",
    civs: [],
  },
  "Great Bombard Emplacement": {
    dmg: 100,
    projectiles: 1,
    rate: 7.12,
    range: 10,
    type: "ranged",
    civs: ["Ottomans"],
  },
  "Arbalest Emplacement": {
    dmg: 40,
    projectiles: 1,
    rate: 1.5,
    range: 9.5,
    type: "ranged",
    civs: ["French", "Jeanne d'Arc"],
  },
  "Trebuchet Emplacement": {
    dmg: 25,
    projectiles: 2,
    rate: 12.12,
    range: 18,
    type: "siege",
    civs: ["Knights Templar"],
  },
};

export const TORCH_BY_AGE = { 2: 13, 3: 17, 4: 21 };
export const TORCH_ATTACK_SPEED = 2.15;

export const KIPCHAK_TRIPLE_SHOT = Object.freeze({
  extraArrows: 2,
  damageMultiplier: 0.3,
  extraBleedDpsPerArrow: 0.6,
  tickInterval: 1,
});

export const POISON_TICK_INTERVAL = 1; // 1 second ticks, same as bleed
