"""Refresh the Champions-only item catalogue; uses the regulation-aware HTTP cache.

Run with --refresh to bypass cached source pages. Mechanics live in item-model.js;
new catalogue entries remain selectable with an explicit unmodeled notice.
"""
import argparse
import html
import json
import re
from datetime import datetime, timezone
from pathlib import Path

import generate_data as g

SOURCE = "https://www.serebii.net/pokemonchampions/items.shtml"


def parse_items(page):
    items = {}
    plain = lambda s: re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", s))).strip()
    for row in re.findall(r"<tr\b[^>]*>(.*?)</tr>", page, re.S | re.I):
        cells = re.findall(r"<td\b[^>]*>(.*?)</td>", row, re.S | re.I)
        for index, cell in enumerate(cells):
            match = re.search(r'<a\b[^>]*href=[\"\'][^\"\']*/itemdex/[^\"\']+[\"\'][^>]*>(.*?)</a>', cell, re.S | re.I)
            if not match or index + 1 >= len(cells):
                continue
            name, effect = plain(match[1]), plain(cells[index + 1])
            if not name or not effect:
                continue
            slug = re.sub(r"[^a-z0-9]+", "-", name.lower().replace("'", "").replace("’", "")).strip("-")
            group = "Mega Stones" if "mega evolve" in effect.lower() else "Berries" if name.endswith("Berry") else "Held items"
            if group == "Held items" and not re.search(r"\bheld\b", effect, re.I):
                continue  # roster tickets / training coupons are not battle-held items
            items[slug] = {"label": name, "group": group}
    if len(items) < 100 or not all(k in items for k in ["leek", "air-balloon", "psychic-seed", "sitrus-berry", "salamencite"]):
        raise ValueError("Incomplete Champions item catalogue; refusing to replace snapshot")
    return dict(sorted(items.items()))


def main():
    args = argparse.ArgumentParser(description=__doc__)
    args.add_argument("--refresh", action="store_true")
    opts = args.parse_args()
    g.REGULATION, g.REFRESH = g.load_regulation(), opts.refresh
    items = parse_items(g.http_json(SOURCE, "champions_items", text=True))
    meta = {"source": SOURCE, "regulation": g.REGULATION["id"], "checkedAt": datetime.now(timezone.utc).date().isoformat()}
    out = Path(__file__).resolve().parents[1] / "src" / "item-catalog.js"
    out.write_text("// Generated by tools/generate_items.py. Do not edit by hand.\n"
                   + "export const ITEM_CATALOG_META = " + json.dumps(meta, ensure_ascii=False) + ";\n"
                   + "export const ITEM_CATALOG = " + json.dumps(items, ensure_ascii=False, indent=2) + ";\n", encoding="utf-8")
    print(f"Wrote {len(items)} Champions items to {out}")
    print(", ".join(v["label"] for v in items.values() if v["group"] != "Mega Stones"))


if __name__ == "__main__":
    main()
