import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { ITEMS, itemDamage, itemAccuracy, itemSpeed, seedEffect, itemAtHit, isGrounded, resistBerry, critChance, normalizeItem, itemSelect, usageItem } from "../src/item-model.js";
import { ITEM_CATALOG } from "../src/item-catalog.js";
import { buildDefensiveProfile } from "../src/team-analysis.js";
const data = JSON.parse(readFileSync(new URL("../champions-data.json", import.meta.url)));
const mon = (slug) => data.pokemon.find((m) => m.slug === slug);
const move = (name) => Object.values(data.moves).find((m) => m.name === name);
const ctx = { type: "steel", cat: "physical", mon: mon("steelix"), ability: null };
assert.equal(itemDamage("metal-coat", ctx), 1.2);
assert.equal(itemDamage("charcoal", ctx), 1);
assert.equal(itemDamage("muscle-band", ctx), 1.1);
assert.equal(itemDamage("wise-glasses", ctx), 1);
assert.equal(itemDamage("muscle-band", { ...ctx, cat: "special" }), 1);
assert.equal(itemDamage("wise-glasses", { ...ctx, cat: "special" }), 1.1);
assert.equal(itemDamage("expert-belt", ctx), 1);
assert.equal(itemDamage("expert-belt", { ...ctx, se: true }), 1.2);
assert.equal(itemDamage("normal-gem", ctx), 1);
assert.equal(itemDamage("normal-gem", { ...ctx, type: "normal" }), 1.3);
assert.equal(itemDamage("normal-gem", { ...ctx, type: "normal", firstUse: false }), 1);
assert.equal(itemDamage("light-ball", { ...ctx, mon: { slug: "pikachu" } }), 2);
assert.equal(itemDamage("light-ball", ctx), 1);
assert.equal(itemDamage("light-ball", { ...ctx, mon: { slug: "pikachu" }, moveName: "Body Press" }), 1);
assert.equal(itemDamage("life-orb", { ...ctx, ability: "klutz" }), 1);
assert.equal(itemDamage("life-orb", { ...ctx, mon: { ...ctx.mon, isMega: true } }), 1);
assert.equal(normalizeItem("life-orb", { isMega: true }), "mega-stone");
assert.equal(normalizeItem("mega-stone", { isMega: false }), "none");
assert.equal(itemAtHit("mega-stone", null, "none"), "mega-stone", "Mega Acrobatics still holds its stone");
assert.equal(normalizeItem("__proto__"), "none");
assert.equal(normalizeItem("not-an-item"), "none");
assert.ok(Math.abs(90 * itemAccuracy("wide-lens") - 99) < 1e-10);
assert.equal(itemAccuracy("wide-lens", "klutz"), 1);
assert.equal(itemAccuracy("zoom-lens", null, false), 1.2);
assert.equal(itemAccuracy("zoom-lens", null, true), 1);
assert.equal(itemAccuracy("zoom-lens", null, null), 1);
for (const [id, terrain, stat] of [["grassy-seed", "grassy", "def"], ["electric-seed", "electric", "def"], ["psychic-seed", "psychic", "spd"], ["misty-seed", "misty", "spd"]]) {
  assert.deepEqual(seedEffect(id, null, terrain), { stat, stages: 1, consumed: true });
  assert.equal(seedEffect(id, "klutz", terrain), null);
  assert.equal(seedEffect(id, null, "none"), null);
  assert.equal(seedEffect(id, "simple", terrain).stages, 2);
  assert.equal(seedEffect(id, "contrary", terrain).stages, -1);
  assert.equal(itemAtHit(id, "unburden", terrain), "none");
  assert.equal(itemSpeed(id, "unburden", terrain), 2);
}
assert.equal(itemSpeed("none", "unburden", "grassy"), 1, "no item is not proof of consumption");
assert.equal(itemSpeed("choice-scarf", null), 1.5);
assert.equal(itemSpeed("iron-ball", null), 0.5);
assert.equal(itemSpeed("iron-ball", "klutz"), 1);
assert.equal(isGrounded(["steel"], null, "air-balloon"), false);
assert.equal(isGrounded(["flying"], "levitate", "iron-ball"), true);
assert.equal(isGrounded(["steel"], "klutz", "air-balloon"), true);
assert.equal(resistBerry("babiri-berry", "steel", 2), 0.5);
assert.equal(resistBerry("babiri-berry", "fire", 2), 1);
assert.equal(resistBerry("babiri-berry", "steel", 1), 1);
assert.equal(resistBerry("chilan-berry", "normal", 1), 0.5);
assert.equal(resistBerry("babiri-berry", "steel", 2, null, "unnerve"), 1);
assert.equal(resistBerry("babiri-berry", "steel", 2, "klutz"), 1);
assert.equal(critChance(move("Close Combat"), "leek", "scrappy", mon("sirfetchd")), 0.5);
assert.equal(critChance(move("Leaf Blade"), "leek", "scrappy", mon("sirfetchd")), 1);
assert.equal(critChance(move("Leaf Blade"), "scope-lens", null, mon("sirfetchd")), 0.5);
assert.equal(critChance(move("Close Combat"), "leek", null, mon("steelix")), 1 / 24);
assert.equal(critChance(move("Leaf Blade"), "leek", "klutz", mon("sirfetchd")), 1 / 8);
assert.equal(critChance(move("Leaf Blade"), "leek", "scrappy", mon("sirfetchd"), "battle-armor"), 0);
const ground = (types, ability, item) => buildDefensiveProfile([{ mon: { types }, ability, item }], data.typeChart).rows.find((r) => r.attackType === "ground").cells[0];
assert.equal(ground(["steel"], null, "air-balloon"), 0);
assert.equal(ground(["steel"], "klutz", "air-balloon"), 2);
assert.equal(ground(["flying", "steel"], null, "iron-ball"), 1);
assert.equal(ground(["steel"], "levitate", "iron-ball"), 2);
assert.equal(usageItem(mon("sirfetchd")), "leek");
const mc = ["air-balloon", "binding-band", "eject-button", "electric-seed", "grassy-seed", "leek", "misty-seed", "normal-gem", "psychic-seed", "red-card", "rocky-helmet", "terrain-extender", "absolite-z", "baxcalibrite", "garchompite-z", "golisopite", "lucarionite-z", "salamencite"];
for (const id of mc) assert.ok(ITEM_CATALOG[id], id);
for (const id of ["choice-band", "choice-specs", "assault-vest", "loaded-dice", "power-herb", "eviolite"]) assert.ok(!ITEM_CATALOG[id], id);
for (const [id, item] of Object.entries(ITEM_CATALOG)) {
  assert.ok(ITEMS[id].note, `No silent unsupported effect: ${id}`);
  assert.ok(!/Ticket|Coupon/.test(item.label));
  assert.match(itemSelect("data-test", id), new RegExp(`value="${id}" selected`));
}
assert.equal((itemSelect("data-test", "life-orb", { isMega: true }).match(/<option /g) || []).length, 1);
assert.ok(!itemSelect("data-test", "none").includes('value="type-item"'));
assert.ok(itemSelect("data-test", "type-item").includes("Legacy:"));
console.log(`item tests passed: ${Object.keys(ITEM_CATALOG).length} catalogue entries; all 18 M-C additions; damage, accuracy, crit, seeds, grounding, speed, berries and legacy presets`);
