import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { selectMetaDataset, teamsForPokemon, mapTournamentTeam, groupTeammates } from "../src/meta-model.js";
import { validSpread, natureMultiplier } from "../src/set-model.js";
import { renderStatRows, ehpValues } from "../src/stat-lab.js";
const read = (file) => JSON.parse(readFileSync(new URL(file, import.meta.url)));
const data = read("../champions-data.json");
data.tournamentMeta = read("../champions-meta.json");
data.tournamentTeams = read("../champions-teams.json");
const gengar = data.pokemon.find((m) => m.slug === "gengar-mega");
assert.ok(data.pokemon.every((m) => !Object.hasOwn(m, "usage") && !Object.hasOwn(m, "usagePct")), "Static data must not contain dynamic usage");
const abilities = structuredClone(gengar.abilities);
assert.equal(selectMetaDataset(data, "M-C"), true);
const mc = structuredClone(gengar.metaUsage);
assert.equal(selectMetaDataset(data, "M-B"), true);
assert.notDeepEqual(gengar.metaUsage.natures, mc.natures);
assert.deepEqual(gengar.abilities, abilities, "Pre-Mega recorded usage must never replace canonical Mega ability");
assert.equal(selectMetaDataset(data, "bogus"), false);
selectMetaDataset(data, "M-C");
assert.ok(teamsForPokemon(data, gengar).every((t) => t.regulation === "M-C"));
assert.ok(gengar.metaUsage.spreads.length > 5);
assert.ok(gengar.metaUsage.moves.length > 5);
const groups = groupTeammates([{ id: "froslass", name: "Froslass", count: 50, percent: 19.8 }, { id: "froslass-mega", name: "Mega Froslass", count: 50, percent: 19.8 }]);
assert.equal(groups.length, 1);
assert.equal(groups[0].base.percent, 19.8, "Never add overlapping base and Mega percentages");
const source = teamsForPokemon(data, gengar).find((t) => !mapTournamentTeam(t, data).errors.length && t.members.some((m) => m.statsKnown));
assert.ok(source, "At least one fully mappable exact build fixture");
const before = JSON.stringify(source), mapped = mapTournamentTeam(source, data);
assert.equal(mapped.members.length, 6);
assert.equal(mapped.name, source.title);
mapped.members.forEach((m, i) => {
  assert.equal(m.slug, source.members[i].form);
  assert.equal(m.nature, source.members[i].nature?.toLowerCase() || null);
  assert.deepEqual(m.spread, source.members[i].statsKnown ? source.members[i].stats : null);
  assert.equal(m.moves.length, source.members[i].moves.length);
});
assert.equal(JSON.stringify(source), before, "Mapping must not mutate raw evidence");
const unknown = structuredClone(source); unknown.members[0].form = "unmapped-form";
assert.ok(mapTournamentTeam(unknown, data).errors.some((e) => e.includes("unmapped-form")));
const missing = structuredClone(source); missing.members[0].statsKnown = false;
assert.equal(mapTournamentTeam(missing, data).members[0].spread, null);
assert.ok(mapTournamentTeam(missing, data).warnings.some((e) => e.includes("undisclosed")));
const mega = structuredClone(source);
mega.members[0] = { ...mega.members[0], pokemon: "gengar-mega", form: "gengar-mega", ability: "cursed-body", item: "gengarite", moves: [] };
const mm = mapTournamentTeam(mega, data).members[0];
assert.equal(mm.ability, "shadow-tag"); assert.equal(mm.sourceAbility, "cursed-body"); assert.equal(mm.sourceItem, "gengarite");
const spread = { hp: 2, atk: 0, def: 0, spa: 32, spd: 0, spe: 32 };
assert.ok(validSpread(spread)); assert.ok(!validSpread({ ...spread, hp: 33 }));
assert.equal(natureMultiplier("timid", "spe"), 1.1);
assert.equal(natureMultiplier("modest", "atk"), 0.9);
assert.equal(natureMultiplier("modest", "hp"), 1);
assert.match(renderStatRows(gengar, spread, "timid"), /pt-meta/);
assert.match(renderStatRows(gengar, spread, "timid"), /share of all allocated points/);
assert.ok(ehpValues(gengar, spread, "bold").phys > ehpValues(gengar, spread, "serious").phys);
console.log("Meta model passed: static isolation, regulation, form grouping, exact sets/import errors, Nature and existing per-stat UI");
