import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { selectMetaDataset, teamsForPokemon, mapTournamentTeam } from "../src/meta-model.js";
import { presentBuilds, presentImportNotes, renderMetaUsage, renderPublishedTeam } from "../src/meta-view.js";
const read = file => JSON.parse(readFileSync(new URL(file, import.meta.url)));
const data = read("../champions-data.json");
data.tournamentMeta = read("../champions-meta.json");
data.tournamentTeams = read("../champions-teams.json");
selectMetaDataset(data, "M-C");
const hydreigon = data.pokemon.find(m => m.slug === "hydreigon");
const florges = data.pokemon.find(m => m.slug === "florges");
const before = JSON.stringify(data);
const build = presentBuilds(hydreigon.metaUsage)[0];
assert.equal(build.percent, 75);
assert.equal(build.evidence.count, 3);
assert.equal(build.evidence.sampleSize, 4);
assert.deepEqual(build.evidence.natures, [{ id: "modest", count: 3, percent: 100 }]);
const hydroHtml = renderMetaUsage(hydreigon, data);
assert.match(hydroHtml, /75%/);
assert.match(hydroHtml, /3\/3/);
assert.match(hydroHtml, /aggregate usage/);
assert.match(hydroHtml, /separate from aggregate sample/);
assert.match(hydroHtml, /75.3%/, "Overall Nature remains a distinct distribution");
assert.equal((hydroHtml.match(/data-build-card/g) || []).length, 2);
assert.match(hydroHtml, /alt="Sneasler"/);
assert.match(hydroHtml, /35.5%/);
const flowerHtml = renderMetaUsage(florges, data, {}, { view: "builds" });
assert.equal(presentBuilds(florges.metaUsage).length, 3);
assert.ok(presentBuilds(florges.metaUsage).every(b => b.evidence === null));
assert.equal((flowerHtml.match(/Nature: unavailable from captured sets/g) || []).length, 3);
assert.doesNotMatch(flowerHtml, /data-meta-joint/);
assert.equal((flowerHtml.match(/data-meta-spread/g) || []).length, 3);
// Aggregate and overall Nature changes may NEVER produce captured evidence.
const aggregateOnly = structuredClone(florges.metaUsage);
aggregateOnly.natures = [{ id: "modest", percent: 100 }];
assert.ok(presentBuilds(aggregateOnly).every(b => b.evidence === null));
const mismatch = structuredClone(hydreigon.metaUsage);
mismatch.observedSpreads[0].stats = { hp: 32, atk: 0, def: 0, spa: 32, spd: 2, spe: 0 };
assert.equal(presentBuilds(mismatch)[0].evidence, null);
assert.equal(presentBuilds(mismatch).at(-1).percent, null, "Captured-only build must not claim aggregate usage");
const browser = renderMetaUsage(hydreigon, data, {}, { view: "teams", teamKind: "tournament" });
assert.match(browser, /data-meta-open-team/);
assert.doesNotMatch(browser, /meta-set-card|data-meta-import=|<details/, "Collapsed browser renders no six-set payloads or duplicate import controls");
assert.equal((browser.match(/data-team-card=/g) || []).length, 6);
assert.equal((browser.match(/class="meta-avatar/g) || []).length, 36);
assert.equal((browser.match(/<img /g) || []).length, 35); // one source Floette form is unmapped; do not substitute another form
assert.match(browser, /Floette — image unavailable/);
const team = teamsForPokemon(data, hydreigon).find(t => !mapTournamentTeam(t, data).errors.length);
const detail = renderPublishedTeam(team, data);
assert.equal((detail.match(/class="meta-set-card"/g) || []).length, 6);
assert.equal((detail.match(/data-meta-import=/g) || []).length, 1);
assert.equal((detail.match(/data-meta-opponent=/g) || []).length, 1);
assert.doesNotMatch(detail, /Stat Points undisclosed|Import notes \(6\)|<details/);
const unknown = structuredClone(team); unknown.members[0].form = "unmapped-test-form";
assert.match(renderPublishedTeam(unknown, data), /Resolve before importing/);
assert.match(renderPublishedTeam(unknown, data), /unmapped-test-form/);
assert.match(renderPublishedTeam(unknown, data), /data-meta-import="[^"]+" disabled/);
const mapping = mapTournamentTeam(team, data), oldWarnings = [...mapping.warnings];
assert.ok(presentImportNotes(mapping).notes.every(note => !note.includes("Stat Points undisclosed")));
assert.deepEqual(mapping.warnings, oldWarnings);
assert.equal(JSON.stringify(data), before, "Rendering must not change raw evidence, mapping, snapshots or mechanics");
console.log("Meta presentation passed: Hydreigon/Florges, exact evidence pairing, missing Nature, sprite cards, focused actions, real errors and data immutability");
