import assert from "node:assert/strict";
import { migrateSavedTeams, saveTeamRecord, emptyTeamContext } from "../src/team-store.js";
let sequence = 0;
const id = () => `test-${++sequence}`;
const old = [{ name: "Team A", members: [{ slug: "steelix", moves: [] }] }, { id: "keep", name: "Team C", members: [] }];
const migrated = migrateSavedTeams(old, id);
assert.ok(migrated[0].id);
assert.equal(migrated[1].id, "keep");
assert.deepEqual(migrateSavedTeams(migrated, id), migrated, "migration stable after persistence");
assert.notEqual(migrateSavedTeams([{ ...migrated[0] }, { ...migrated[0] }], id)[1].id, migrated[0].id);
const context = { loadedId: migrated[0].id, originalName: "Team A", name: "Team A" };
const members = [{ slug: "sirfetchd", moves: [1], item: "leek", nature: "adamant", spread: { hp: 2, atk: 32, def: 0, spa: 0, spd: 0, spe: 32 } }];
const updated = saveTeamRecord(migrated, context, members, id);
assert.equal(updated.records.length, 2);
assert.equal(updated.context.loadedId, context.loadedId);
assert.deepEqual(updated.records[0].members, members);
members[0].moves.push(3);
assert.deepEqual(updated.records[0].members[0].moves, [1], "snapshot is not aliased to working team");
const copied = saveTeamRecord(updated.records, { ...context, name: "Team B" }, members, id);
assert.equal(copied.records.length, 3);
assert.notEqual(copied.context.loadedId, context.loadedId);
assert.equal(copied.context.originalName, "Team B");
assert.deepEqual(copied.records[0], updated.records[0], "Save As preserves original");
assert.ok(saveTeamRecord(copied.records, { ...copied.context, name: "Team A" }, members, id).error);
assert.ok(saveTeamRecord(copied.records, emptyTeamContext("team a"), members, id).error);
assert.equal(saveTeamRecord([], emptyTeamContext("Imported"), members, id).action, "created");
assert.ok(saveTeamRecord([], emptyTeamContext(), members, id).error);
assert.ok(saveTeamRecord([], emptyTeamContext("Empty"), [], id).error);
assert.equal(old[0].id, undefined, "migration never mutates the source");
console.log("team-store tests passed: stable IDs, migration, update, Save As, conflicts, unsaved import");
