"use strict";

// Card art from the Tabletop Simulator mod, when it is on disk.
//
// assets/card-art.json records where every card sits on its sprite sheet
// (generated by tools/extract-mod.py --card-art). The sheets themselves are not
// committed — they are scans of published Fantasy Flight artwork — so
// tools/fetch-mod-assets.sh downloads them into assets/mod/ on your own machine.
//
// With the sheets absent every lookup returns "", the cards keep their drawn
// faces, and nothing anywhere needs to know the difference.

(function () {
  const BASE = "assets/mod/";
  let manifest = null;
  let ready = false;

  // Percentage sprite maths: with background-size scaled up by the grid, the
  // cell at (row, col) sits col/(cols-1) of the way across the sheet.
  function styleFor(entry) {
    if (!entry || !manifest || !manifest.sheets[entry.sheet]) return "";
    const x = entry.cols > 1 ? (entry.col / (entry.cols - 1)) * 100 : 0;
    const y = entry.rows > 1 ? (entry.row / (entry.rows - 1)) * 100 : 0;
    return "background-image:url(" + BASE + entry.sheet + ".jpg);" +
      "background-size:" + (entry.cols * 100) + "% " + (entry.rows * 100) + "%;" +
      "background-position:" + x.toFixed(4) + "% " + y.toFixed(4) + "%;";
  }

  // One probe decides it for the whole session: if the first sheet is missing,
  // no card asks again.
  function probe() {
    if (!manifest) return Promise.resolve(false);
    const first = Object.keys(manifest.sheets)[0];
    if (!first) return Promise.resolve(false);
    return new Promise((resolve) => {
      const img = new Image();
      img.onload = () => { ready = true; resolve(true); };
      img.onerror = () => { ready = false; resolve(false); };
      img.src = BASE + first + ".jpg";
    });
  }

  const CivCardArt = {
    // Resolves to whether the art is usable, so a caller can re-render once.
    load() {
      return fetch("assets/card-art.json", { cache: "force-cache" })
        .then((r) => (r.ok ? r.json() : null))
        .then((m) => { manifest = m; return probe(); })
        .catch(() => false);
    },
    available: () => ready,
    focus(type, tier) {
      return ready && manifest ? styleFor(manifest.focus[type + "-" + tier]) : "";
    },
    unique(leaderId) {
      return ready && manifest ? styleFor(manifest.unique[String(leaderId).toLowerCase()]) : "";
    },
    wonder(name) {
      return ready && manifest ? styleFor(manifest.wonders[name]) : "";
    }
  };

  window.CivCardArt = CivCardArt;
})();
