// Generated by tools/generate_items.py. Do not edit by hand.
export const ITEM_CATALOG_META = {"source": "https://www.serebii.net/pokemonchampions/items.shtml", "regulation": "M-C", "checkedAt": "2026-09-13"};
export const ITEM_CATALOG = {
  "abomasite": {
    "label": "Abomasite",
    "group": "Mega Stones"
  },
  "absolite": {
    "label": "Absolite",
    "group": "Mega Stones"
  },
  "absolite-z": {
    "label": "Absolite Z",
    "group": "Mega Stones"
  },
  "aerodactylite": {
    "label": "Aerodactylite",
    "group": "Mega Stones"
  },
  "aggronite": {
    "label": "Aggronite",
    "group": "Mega Stones"
  },
  "air-balloon": {
    "label": "Air Balloon",
    "group": "Held items"
  },
  "alakazite": {
    "label": "Alakazite",
    "group": "Mega Stones"
  },
  "altarianite": {
    "label": "Altarianite",
    "group": "Mega Stones"
  },
  "ampharosite": {
    "label": "Ampharosite",
    "group": "Mega Stones"
  },
  "aspear-berry": {
    "label": "Aspear Berry",
    "group": "Berries"
  },
  "audinite": {
    "label": "Audinite",
    "group": "Mega Stones"
  },
  "babiri-berry": {
    "label": "Babiri Berry",
    "group": "Berries"
  },
  "banettite": {
    "label": "Banettite",
    "group": "Mega Stones"
  },
  "barbaracite": {
    "label": "Barbaracite",
    "group": "Mega Stones"
  },
  "baxcalibrite": {
    "label": "Baxcalibrite",
    "group": "Mega Stones"
  },
  "beedrillite": {
    "label": "Beedrillite",
    "group": "Mega Stones"
  },
  "big-root": {
    "label": "Big Root",
    "group": "Held items"
  },
  "binding-band": {
    "label": "Binding Band",
    "group": "Held items"
  },
  "black-belt": {
    "label": "Black Belt",
    "group": "Held items"
  },
  "black-glasses": {
    "label": "Black Glasses",
    "group": "Held items"
  },
  "blastoisinite": {
    "label": "Blastoisinite",
    "group": "Mega Stones"
  },
  "blazikenite": {
    "label": "Blazikenite",
    "group": "Mega Stones"
  },
  "bright-powder": {
    "label": "Bright Powder",
    "group": "Held items"
  },
  "cameruptite": {
    "label": "Cameruptite",
    "group": "Mega Stones"
  },
  "chandelurite": {
    "label": "Chandelurite",
    "group": "Mega Stones"
  },
  "charcoal": {
    "label": "Charcoal",
    "group": "Held items"
  },
  "charizardite-x": {
    "label": "Charizardite X",
    "group": "Mega Stones"
  },
  "charizardite-y": {
    "label": "Charizardite Y",
    "group": "Mega Stones"
  },
  "charti-berry": {
    "label": "Charti Berry",
    "group": "Berries"
  },
  "cheri-berry": {
    "label": "Cheri Berry",
    "group": "Berries"
  },
  "chesnaughtite": {
    "label": "Chesnaughtite",
    "group": "Mega Stones"
  },
  "chesto-berry": {
    "label": "Chesto Berry",
    "group": "Berries"
  },
  "chilan-berry": {
    "label": "Chilan Berry",
    "group": "Berries"
  },
  "chimechite": {
    "label": "Chimechite",
    "group": "Mega Stones"
  },
  "choice-scarf": {
    "label": "Choice Scarf",
    "group": "Held items"
  },
  "chople-berry": {
    "label": "Chople Berry",
    "group": "Berries"
  },
  "clefablite": {
    "label": "Clefablite",
    "group": "Mega Stones"
  },
  "coba-berry": {
    "label": "Coba Berry",
    "group": "Berries"
  },
  "colbur-berry": {
    "label": "Colbur Berry",
    "group": "Berries"
  },
  "crabominite": {
    "label": "Crabominite",
    "group": "Mega Stones"
  },
  "damp-rock": {
    "label": "Damp Rock",
    "group": "Held items"
  },
  "delphoxite": {
    "label": "Delphoxite",
    "group": "Mega Stones"
  },
  "dragalgite": {
    "label": "Dragalgite",
    "group": "Mega Stones"
  },
  "dragon-fang": {
    "label": "Dragon Fang",
    "group": "Held items"
  },
  "dragoninite": {
    "label": "Dragoninite",
    "group": "Mega Stones"
  },
  "drampanite": {
    "label": "Drampanite",
    "group": "Mega Stones"
  },
  "eelektrossite": {
    "label": "Eelektrossite",
    "group": "Mega Stones"
  },
  "eject-button": {
    "label": "Eject Button",
    "group": "Held items"
  },
  "electric-seed": {
    "label": "Electric Seed",
    "group": "Held items"
  },
  "emboarite": {
    "label": "Emboarite",
    "group": "Mega Stones"
  },
  "excadrite": {
    "label": "Excadrite",
    "group": "Mega Stones"
  },
  "expert-belt": {
    "label": "Expert Belt",
    "group": "Held items"
  },
  "fairy-feather": {
    "label": "Fairy Feather",
    "group": "Held items"
  },
  "falinksite": {
    "label": "Falinksite",
    "group": "Mega Stones"
  },
  "feraligite": {
    "label": "Feraligite",
    "group": "Mega Stones"
  },
  "floettite": {
    "label": "Floettite",
    "group": "Mega Stones"
  },
  "focus-band": {
    "label": "Focus Band",
    "group": "Held items"
  },
  "focus-sash": {
    "label": "Focus Sash",
    "group": "Held items"
  },
  "froslassite": {
    "label": "Froslassite",
    "group": "Mega Stones"
  },
  "galladite": {
    "label": "Galladite",
    "group": "Mega Stones"
  },
  "garchompite": {
    "label": "Garchompite",
    "group": "Mega Stones"
  },
  "garchompite-z": {
    "label": "Garchompite Z",
    "group": "Mega Stones"
  },
  "gardevoirite": {
    "label": "Gardevoirite",
    "group": "Mega Stones"
  },
  "gengarite": {
    "label": "Gengarite",
    "group": "Mega Stones"
  },
  "glalitite": {
    "label": "Glalitite",
    "group": "Mega Stones"
  },
  "glimmoranite": {
    "label": "Glimmoranite",
    "group": "Mega Stones"
  },
  "golisopite": {
    "label": "Golisopite",
    "group": "Mega Stones"
  },
  "golurkite": {
    "label": "Golurkite",
    "group": "Mega Stones"
  },
  "grassy-seed": {
    "label": "Grassy Seed",
    "group": "Held items"
  },
  "greninjite": {
    "label": "Greninjite",
    "group": "Mega Stones"
  },
  "gyaradosite": {
    "label": "Gyaradosite",
    "group": "Mega Stones"
  },
  "haban-berry": {
    "label": "Haban Berry",
    "group": "Berries"
  },
  "hard-stone": {
    "label": "Hard Stone",
    "group": "Held items"
  },
  "hawluchanite": {
    "label": "Hawluchanite",
    "group": "Mega Stones"
  },
  "heat-rock": {
    "label": "Heat Rock",
    "group": "Held items"
  },
  "heracronite": {
    "label": "Heracronite",
    "group": "Mega Stones"
  },
  "houndoominite": {
    "label": "Houndoominite",
    "group": "Mega Stones"
  },
  "icy-rock": {
    "label": "Icy Rock",
    "group": "Held items"
  },
  "iron-ball": {
    "label": "Iron Ball",
    "group": "Held items"
  },
  "kangaskhanite": {
    "label": "Kangaskhanite",
    "group": "Mega Stones"
  },
  "kasib-berry": {
    "label": "Kasib Berry",
    "group": "Berries"
  },
  "kebia-berry": {
    "label": "Kebia Berry",
    "group": "Berries"
  },
  "kings-rock": {
    "label": "King's Rock",
    "group": "Held items"
  },
  "leek": {
    "label": "Leek",
    "group": "Held items"
  },
  "leftovers": {
    "label": "Leftovers",
    "group": "Held items"
  },
  "leppa-berry": {
    "label": "Leppa Berry",
    "group": "Berries"
  },
  "life-orb": {
    "label": "Life Orb",
    "group": "Held items"
  },
  "light-ball": {
    "label": "Light Ball",
    "group": "Held items"
  },
  "light-clay": {
    "label": "Light Clay",
    "group": "Held items"
  },
  "lopunnite": {
    "label": "Lopunnite",
    "group": "Mega Stones"
  },
  "lucarionite": {
    "label": "Lucarionite",
    "group": "Mega Stones"
  },
  "lucarionite-z": {
    "label": "Lucarionite Z",
    "group": "Mega Stones"
  },
  "lum-berry": {
    "label": "Lum Berry",
    "group": "Berries"
  },
  "magnet": {
    "label": "Magnet",
    "group": "Held items"
  },
  "malamarite": {
    "label": "Malamarite",
    "group": "Mega Stones"
  },
  "manectite": {
    "label": "Manectite",
    "group": "Mega Stones"
  },
  "mawilite": {
    "label": "Mawilite",
    "group": "Mega Stones"
  },
  "medichamite": {
    "label": "Medichamite",
    "group": "Mega Stones"
  },
  "meganiumite": {
    "label": "Meganiumite",
    "group": "Mega Stones"
  },
  "mental-herb": {
    "label": "Mental Herb",
    "group": "Held items"
  },
  "meowsticite": {
    "label": "Meowsticite",
    "group": "Mega Stones"
  },
  "metagrossite": {
    "label": "Metagrossite",
    "group": "Mega Stones"
  },
  "metal-coat": {
    "label": "Metal Coat",
    "group": "Held items"
  },
  "metronome": {
    "label": "Metronome",
    "group": "Held items"
  },
  "miracle-seed": {
    "label": "Miracle Seed",
    "group": "Held items"
  },
  "misty-seed": {
    "label": "Misty Seed",
    "group": "Held items"
  },
  "muscle-band": {
    "label": "Muscle Band",
    "group": "Held items"
  },
  "mystic-water": {
    "label": "Mystic Water",
    "group": "Held items"
  },
  "never-melt-ice": {
    "label": "Never-Melt Ice",
    "group": "Held items"
  },
  "normal-gem": {
    "label": "Normal Gem",
    "group": "Held items"
  },
  "occa-berry": {
    "label": "Occa Berry",
    "group": "Berries"
  },
  "oran-berry": {
    "label": "Oran Berry",
    "group": "Berries"
  },
  "passho-berry": {
    "label": "Passho Berry",
    "group": "Berries"
  },
  "payapa-berry": {
    "label": "Payapa Berry",
    "group": "Berries"
  },
  "pecha-berry": {
    "label": "Pecha Berry",
    "group": "Berries"
  },
  "persim-berry": {
    "label": "Persim Berry",
    "group": "Berries"
  },
  "pidgeotite": {
    "label": "Pidgeotite",
    "group": "Mega Stones"
  },
  "pinsirite": {
    "label": "Pinsirite",
    "group": "Mega Stones"
  },
  "poison-barb": {
    "label": "Poison Barb",
    "group": "Held items"
  },
  "psychic-seed": {
    "label": "Psychic Seed",
    "group": "Held items"
  },
  "pyroarite": {
    "label": "Pyroarite",
    "group": "Mega Stones"
  },
  "quick-claw": {
    "label": "Quick Claw",
    "group": "Held items"
  },
  "raichunite-x": {
    "label": "Raichunite X",
    "group": "Mega Stones"
  },
  "raichunite-y": {
    "label": "Raichunite Y",
    "group": "Mega Stones"
  },
  "rawst-berry": {
    "label": "Rawst Berry",
    "group": "Berries"
  },
  "red-card": {
    "label": "Red Card",
    "group": "Held items"
  },
  "rindo-berry": {
    "label": "Rindo Berry",
    "group": "Berries"
  },
  "rocky-helmet": {
    "label": "Rocky Helmet",
    "group": "Held items"
  },
  "roseli-berry": {
    "label": "Roseli Berry",
    "group": "Berries"
  },
  "sablenite": {
    "label": "Sablenite",
    "group": "Mega Stones"
  },
  "salamencite": {
    "label": "Salamencite",
    "group": "Mega Stones"
  },
  "sceptilite": {
    "label": "Sceptilite",
    "group": "Mega Stones"
  },
  "scizorite": {
    "label": "Scizorite",
    "group": "Mega Stones"
  },
  "scolipite": {
    "label": "Scolipite",
    "group": "Mega Stones"
  },
  "scope-lens": {
    "label": "Scope Lens",
    "group": "Held items"
  },
  "scovillainite": {
    "label": "Scovillainite",
    "group": "Mega Stones"
  },
  "scraftinite": {
    "label": "Scraftinite",
    "group": "Mega Stones"
  },
  "sharp-beak": {
    "label": "Sharp Beak",
    "group": "Held items"
  },
  "sharpedonite": {
    "label": "Sharpedonite",
    "group": "Mega Stones"
  },
  "shed-shell": {
    "label": "Shed Shell",
    "group": "Held items"
  },
  "shell-bell": {
    "label": "Shell Bell",
    "group": "Held items"
  },
  "shuca-berry": {
    "label": "Shuca Berry",
    "group": "Berries"
  },
  "silk-scarf": {
    "label": "Silk Scarf",
    "group": "Held items"
  },
  "silver-powder": {
    "label": "Silver Powder",
    "group": "Held items"
  },
  "sitrus-berry": {
    "label": "Sitrus Berry",
    "group": "Berries"
  },
  "skarmorite": {
    "label": "Skarmorite",
    "group": "Mega Stones"
  },
  "slowbronite": {
    "label": "Slowbronite",
    "group": "Mega Stones"
  },
  "smooth-rock": {
    "label": "Smooth Rock",
    "group": "Held items"
  },
  "soft-sand": {
    "label": "Soft Sand",
    "group": "Held items"
  },
  "spell-tag": {
    "label": "Spell Tag",
    "group": "Held items"
  },
  "staraptite": {
    "label": "Staraptite",
    "group": "Mega Stones"
  },
  "starminite": {
    "label": "Starminite",
    "group": "Mega Stones"
  },
  "steelixite": {
    "label": "Steelixite",
    "group": "Mega Stones"
  },
  "swampertite": {
    "label": "Swampertite",
    "group": "Mega Stones"
  },
  "tanga-berry": {
    "label": "Tanga Berry",
    "group": "Berries"
  },
  "terrain-extender": {
    "label": "Terrain Extender",
    "group": "Held items"
  },
  "twisted-spoon": {
    "label": "Twisted Spoon",
    "group": "Held items"
  },
  "tyranitarite": {
    "label": "Tyranitarite",
    "group": "Mega Stones"
  },
  "venusaurite": {
    "label": "Venusaurite",
    "group": "Mega Stones"
  },
  "victreebelite": {
    "label": "Victreebelite",
    "group": "Mega Stones"
  },
  "wacan-berry": {
    "label": "Wacan Berry",
    "group": "Berries"
  },
  "white-herb": {
    "label": "White Herb",
    "group": "Held items"
  },
  "wide-lens": {
    "label": "Wide Lens",
    "group": "Held items"
  },
  "wise-glasses": {
    "label": "Wise Glasses",
    "group": "Held items"
  },
  "yache-berry": {
    "label": "Yache Berry",
    "group": "Berries"
  },
  "zoom-lens": {
    "label": "Zoom Lens",
    "group": "Held items"
  }
};
